import {
  type IDsqlCluster,
  PreviewableApp,
  type Stage,
} from '@borso/infra';
import { Duration, RemovalPolicy } from 'aws-cdk-lib';
import { BlockPublicAccess, Bucket, BucketEncryption, HttpMethods, ObjectOwnership } from 'aws-cdk-lib/aws-s3';
import { Secret } from 'aws-cdk-lib/aws-secretsmanager';
import type { Construct } from 'constructs';

const APP_SLUG = 'last-loop-lepin';
// One scrypt-hashed PIN shared across every stage (preview/integ/prod).
// Operator-managed via the AWS Secrets Manager console / CLI — the CDK
// stack reads it at deploy time, it never lives in code or workflow env.
// Rotate with `put-secret-value` + redeploy. See
// docs/knowledge/preview-api-cross-origin.md neighbours for context.
const ADMIN_PIN_HASH_SECRET_NAME = `${APP_SLUG}/admin-pin-hash`;

export interface BuildAppStackProps {
  readonly scope: Construct;
  readonly stage: Stage;
  readonly prNumber?: number;
  readonly domainName: string | undefined;
  readonly assetsPath: string;
  readonly apiEntry: string;
  readonly migrationsPath: string;
  readonly cluster: IDsqlCluster;
}

/**
 * Composes the StaticSite + LambdaApi + DsqlSchema for the app, plus the
 * S3 bucket the admin uploads runner photos to.
 *
 * The `LASTLOOP_ALLOW_TEST_SEED` env var is set on the Lambda for every
 * deploy stage EXCEPT `prod` — verified by `stack.test.ts`. Same shape
 * for the JWT secret (a per-stack random in dev/preview, a Secrets
 * Manager-resolved value in prod is expected for future hardening; for
 * now the secret is generated by CDK as a CloudFormation random string).
 */
export function buildLastLoopLepinAppStack(props: BuildAppStackProps): void {
  const photosBucket = new Bucket(props.scope, 'PhotosBucket', {
    bucketName: `${APP_SLUG}-${props.stage}-photos${props.prNumber !== undefined ? `-${props.prNumber}` : ''}`,
    encryption: BucketEncryption.S3_MANAGED,
    blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
    objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED,
    removalPolicy: props.stage === 'prod' ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,
    autoDeleteObjects: props.stage !== 'prod',
    cors: [
      {
        allowedMethods: [HttpMethods.PUT, HttpMethods.GET],
        allowedOrigins: ['*'],
        allowedHeaders: ['*'],
        maxAge: 300,
      },
    ],
    lifecycleRules: [{ abortIncompleteMultipartUploadAfter: Duration.days(1) }],
  });

  const jwtSecret = new Secret(props.scope, 'AdminJwtSecret', {
    secretName: `${APP_SLUG}/${props.stage}/admin-jwt-secret`,
    generateSecretString: {
      passwordLength: 64,
      excludePunctuation: false,
      requireEachIncludedType: false,
    },
  });

  // PIN hash is operator-owned (Hugo). The stack consumes the Secrets
  // Manager value at deploy time — same secret for every stage — and the
  // Lambda receives `PIN_HASH` as a plaintext env var. To rotate without
  // touching this code:
  //   aws secretsmanager put-secret-value \
  //     --secret-id last-loop-lepin/admin-pin-hash \
  //     --secret-string 'scrypt$<salt>$<key>'
  //   # then redeploy so CFN picks up the new value.
  const pinHashSecret = Secret.fromSecretNameV2(
    props.scope,
    'AdminPinHashSecret',
    ADMIN_PIN_HASH_SECRET_NAME,
  );

  const allowSeedFlag: Record<string, string> =
    props.stage === 'prod' ? {} : { LASTLOOP_ALLOW_TEST_SEED: '1' };

  const previewableApp = new PreviewableApp(props.scope, 'App', {
    app: APP_SLUG,
    stage: props.stage,
    ...(props.prNumber !== undefined ? { prNumber: props.prNumber } : {}),
    ...(props.domainName !== undefined ? { domainName: props.domainName } : {}),
    frontend: { distPath: props.assetsPath },
    api: {
      entry: props.apiEntry,
      environment: {
        PHOTOS_BUCKET: photosBucket.bucketName,
        JWT_SECRET: jwtSecret.secretValue.unsafeUnwrap(),
        PIN_HASH: pinHashSecret.secretValue.unsafeUnwrap(),
        ...allowSeedFlag,
      },
    },
    database: {
      migrationsPath: props.migrationsPath,
      cluster: props.cluster,
    },
  });

  if (previewableApp.api !== undefined) {
    photosBucket.grantPut(previewableApp.api.handler);
    photosBucket.grantRead(previewableApp.api.handler);
    jwtSecret.grantRead(previewableApp.api.handler);
    pinHashSecret.grantRead(previewableApp.api.handler);
  }
}
