import {
  type IDsqlCluster,
  PreviewableApp,
  type Stage,
} from '@borso/infra';
import { Duration, RemovalPolicy } from 'aws-cdk-lib';
import { BlockPublicAccess, Bucket, BucketEncryption, HttpMethods, ObjectOwnership } from 'aws-cdk-lib/aws-s3';
import { Secret } from 'aws-cdk-lib/aws-secretsmanager';
import { StringParameter } from 'aws-cdk-lib/aws-ssm';
import type { Construct } from 'constructs';

const APP_SLUG = 'last-loop-lepin';
// One scrypt-hashed PIN shared across every stage (preview/integ/prod).
// Operator-managed via the AWS SSM Parameter Store console / CLI — the
// CDK stack reads it at deploy time, it never lives in code or workflow
// env. Stored as a plain `String` SSM parameter (not `SecureString`)
// because:
//   1. CFN dynamic refs `{{resolve:ssm-secure:…}}` are NOT supported in
//      `AWS::Lambda::Function.Environment.Variables` (CFN explicit deny).
//   2. The value is already a scrypt hash, so at-rest KMS encryption adds
//      defense-in-depth but isn't load-bearing — IAM access control is
//      the same for both String and SecureString.
// Free under the SSM Standard tier (up to 10k parameters). Save $0.40/mo
// vs. Secrets Manager which used to host this value.
const ADMIN_PIN_HASH_PARAMETER_NAME = `/borso/${APP_SLUG}/admin-pin-hash`;

export interface BuildAppStackProps {
  readonly scope: Construct;
  readonly stage: Stage;
  readonly prNumber?: number;
  readonly domainName: string | undefined;
  readonly assetsPath: string;
  readonly apiEntry: string;
  readonly migrationsPath: string;
  readonly cluster: IDsqlCluster;
}

/**
 * Composes the StaticSite + LambdaApi + DsqlSchema for the app, plus the
 * S3 bucket the admin uploads runner photos to.
 *
 * The `LASTLOOP_ALLOW_TEST_SEED` env var is set on the Lambda for every
 * deploy stage EXCEPT `prod` — verified by `stack.test.ts`.
 *
 * Two secrets feed the Lambda:
 *   - `JWT_SECRET`: per-stage random, generated by CDK and stored in
 *     Secrets Manager (CDK's `Secret.generateSecretString` does the
 *     random + KMS encryption out of the box). Costs $0.40/mo/stage.
 *   - `PIN_HASH`: stage-shared, operator-owned, stored in SSM Parameter
 *     Store Standard `String` (free up to 10k parameters). Value is
 *     already a scrypt hash so plaintext-at-rest is acceptable; IAM
 *     access control is the same as a SecureString would give.
 */
export function buildLastLoopLepinAppStack(props: BuildAppStackProps): void {
  const photosBucket = new Bucket(props.scope, 'PhotosBucket', {
    bucketName: `${APP_SLUG}-${props.stage}-photos${props.prNumber !== undefined ? `-${props.prNumber}` : ''}`,
    encryption: BucketEncryption.S3_MANAGED,
    blockPublicAccess: BlockPublicAccess.BLOCK_ALL,
    objectOwnership: ObjectOwnership.BUCKET_OWNER_ENFORCED,
    removalPolicy: props.stage === 'prod' ? RemovalPolicy.RETAIN : RemovalPolicy.DESTROY,
    autoDeleteObjects: props.stage !== 'prod',
    cors: [
      {
        allowedMethods: [HttpMethods.PUT, HttpMethods.GET],
        allowedOrigins: ['*'],
        allowedHeaders: ['*'],
        maxAge: 300,
      },
    ],
    lifecycleRules: [{ abortIncompleteMultipartUploadAfter: Duration.days(1) }],
  });

  const jwtSecret = new Secret(props.scope, 'AdminJwtSecret', {
    secretName: `${APP_SLUG}/${props.stage}/admin-jwt-secret`,
    generateSecretString: {
      passwordLength: 64,
      excludePunctuation: false,
      requireEachIncludedType: false,
    },
  });

  // PIN hash is operator-owned (Hugo). The stack consumes the SSM
  // parameter at deploy time — same value for every stage — and the
  // Lambda receives `PIN_HASH` as a plaintext env var resolved by CFN
  // via `{{resolve:ssm:…}}`. To rotate without touching this code:
  //   aws ssm put-parameter --overwrite --type String \
  //     --name /borso/last-loop-lepin/admin-pin-hash \
  //     --value 'scrypt$<salt>$<key>'
  //   # then redeploy so CFN picks up the new value.
  const pinHashParameter = StringParameter.fromStringParameterAttributes(
    props.scope,
    'AdminPinHashParameter',
    { parameterName: ADMIN_PIN_HASH_PARAMETER_NAME },
  );

  const allowSeedFlag: Record<string, string> =
    props.stage === 'prod' ? {} : { LASTLOOP_ALLOW_TEST_SEED: '1' };

  const previewableApp = new PreviewableApp(props.scope, 'App', {
    app: APP_SLUG,
    stage: props.stage,
    ...(props.prNumber !== undefined ? { prNumber: props.prNumber } : {}),
    ...(props.domainName !== undefined ? { domainName: props.domainName } : {}),
    frontend: { distPath: props.assetsPath },
    api: {
      entry: props.apiEntry,
      environment: {
        PHOTOS_BUCKET: photosBucket.bucketName,
        JWT_SECRET: jwtSecret.secretValue.unsafeUnwrap(),
        PIN_HASH: pinHashParameter.stringValue,
        ...allowSeedFlag,
      },
    },
    database: {
      migrationsPath: props.migrationsPath,
      cluster: props.cluster,
    },
  });

  if (previewableApp.api !== undefined) {
    photosBucket.grantPut(previewableApp.api.handler);
    photosBucket.grantRead(previewableApp.api.handler);
    jwtSecret.grantRead(previewableApp.api.handler);
    // No runtime IAM grant needed for the PIN hash: it's baked into the
    // Lambda env var at deploy time via the CFN `{{resolve:ssm:…}}`
    // dynamic reference, so the Lambda role never touches SSM at runtime.
  }
}
