import { describe, expect, it } from 'vitest';
import {
  renderGrid,
  renderWeakPointPage,
  type PlacedDot,
  type WeakPointPageInput,
} from './weak-points-page.core';
import type { DefectDot } from './weak-points.core';

const NOW = '2026-10-10';

function buildDot(slug: string, overrides: Partial<DefectDot> = {}): DefectDot {
  return {
    slug,
    title: `Title of ${slug}`,
    date: '2026-10-01',
    zone: 'CLAUDE.md',
    weakPoint: null,
    recurs: [],
    ...overrides,
  };
}

function place(dot: DefectDot, map: 'product' | 'factory', row: string, column: string): PlacedDot {
  return { dot, map, row, column };
}

const ENGAGED = {
  id: 'gate-measures-nothing',
  title: 'A gate <measures> nothing',
  map: 'factory',
  engagedOn: '2026-10-10',
  countermeasure: 'Plant a defect',
  isClosed: false,
};

function renderRecentDot(slug: string): string {
  return `<a class="dot recent" href="https://github.com/hugoleborso/borso.fr/blob/main/docs/dantotsus/${slug}.md" title="2026-10-01 · Title of ${slug}" aria-label="2026-10-01 · Title of ${slug}"></a>`;
}

function buildInput(overrides: Partial<WeakPointPageInput> = {}): WeakPointPageInput {
  return {
    now: NOW,
    placed: [
      place(
        buildDot('fresh', { weakPoint: 'gate-measures-nothing' }),
        'factory',
        'gates',
        'defects',
      ),
      place(buildDot('old', { date: '2026-05-01' }), 'factory', 'hooks', 'defects'),
      place(buildDot('core-a', { date: '2026-09-11' }), 'product', 'apps/pragma', 'core'),
      place(buildDot('core-b'), 'product', 'apps/pragma', 'core'),
      place(buildDot('site'), 'product', 'apps/talos', 'site'),
      place(buildDot('route'), 'product', 'apps/talos', 'route'),
      place(buildDot('route-b'), 'product', 'apps/talos', 'route'),
    ],
    engaged: [ENGAGED, { ...ENGAGED, id: 'closed-one', title: 'Closed one', isClosed: true }],
    weeklyCounts: new Map([
      [
        'gate-measures-nothing',
        [
          { weekStart: '2026-09-28', count: 2 },
          { weekStart: '2026-10-05', count: 0 },
        ],
      ],
    ]),
    recurrences: [{ slugs: ['first', 'second'], firstDate: '2026-09-01', lastDate: '2026-09-02' }],
    ...overrides,
  };
}

describe('renderGrid', () => {
  it('draws one dot per defect in its cell, with the row total in the header', () => {
    const placed = [
      place(buildDot('a'), 'product', 'apps/pragma', 'core'),
      place(buildDot('b', { date: '2026-01-01' }), 'product', 'apps/pragma', 'site'),
    ];
    const html = renderGrid(placed, ['apps/pragma'], ['core', 'site'], NOW);
    expect(html).toBe(
      '<div class="scroll"><table><tr><th></th><th>core</th><th>site</th></tr><tr><th>apps/pragma (2)</th>' +
        '<td class="cell"><a class="dot recent" href="https://github.com/hugoleborso/borso.fr/blob/main/docs/dantotsus/a.md" title="2026-10-01 · Title of a" aria-label="2026-10-01 · Title of a"></a></td>' +
        '<td class="cell"><a class="dot" href="https://github.com/hugoleborso/borso.fr/blob/main/docs/dantotsus/b.md" title="2026-01-01 · Title of b" aria-label="2026-01-01 · Title of b"></a></td></tr></table></div>',
    );
  });

  it('marks a dot that belongs to a weak point, and escapes its title', () => {
    const placed = [
      place(buildDot('a', { title: 'a <b> & "c"', weakPoint: 'x' }), 'factory', 'gates', 'defects'),
    ];
    const html = renderGrid(placed, ['gates'], ['defects'], NOW);
    expect(html).toContain('class="dot recent engaged"');
    expect(html).toContain('title="2026-10-01 · a &lt;b&gt; &amp; &quot;c&quot;"');
  });

  it('keeps a dot exactly thirty days old as recent, and one older as faded', () => {
    const placed = [
      place(buildDot('edge', { date: '2026-09-10' }), 'factory', 'gates', 'defects'),
      place(buildDot('past', { date: '2026-09-09' }), 'factory', 'gates', 'defects'),
    ];
    const html = renderGrid(placed, ['gates'], ['defects'], NOW);
    expect(html).toContain(
      '<a class="dot recent" href="https://github.com/hugoleborso/borso.fr/blob/main/docs/dantotsus/edge.md"',
    );
    expect(html).toContain(
      '<a class="dot" href="https://github.com/hugoleborso/borso.fr/blob/main/docs/dantotsus/past.md"',
    );
  });
});

function renderDefault(): string {
  return renderWeakPointPage(buildInput());
}

describe('renderWeakPointPage', () => {
  it('opens with the title and the generation line', () => {
    const html = renderDefault();
    expect(html).toContain('<title>Weak points</title>');
    expect(html).toContain('<h1>Weak points</h1>');
    expect(html).toContain(
      'Generated by scripts/quality/weak-points.ts on 2026-10-10 from 7 dantotsus.',
    );
    expect(html).toContain('A full dot is under 30 days old');
  });

  it('shows each open weak point with its weekly bars and its current week, and skips a closed one', () => {
    const html = renderDefault();
    expect(html).toContain(
      '<h3>A gate &lt;measures&gt; nothing <code>gate-measures-nothing</code></h3>',
    );
    expect(html).toContain(
      'factory map · engaged on 2026-10-10 · 2 occurrence(s) recorded · countermeasure: Plant a defect',
    );
    expect(html).toContain(
      '<span class="bar" style="height:100%" title="week of 2026-09-28: 2"></span>',
    );
    expect(html).toContain(
      '<span class="bar zero" style="height:0%" title="week of 2026-10-05: 0"></span>',
    );
    expect(html).toContain('<p>0 in the week of 2026-10-05. Target: zero per week.</p>');
    expect(html).not.toContain('Closed one');
  });

  it('orders the product rows and columns by how many dots they hold', () => {
    const html = renderDefault();
    expect(html).toContain(
      '<tr><th></th><th>core</th><th>route</th><th>site</th></tr><tr><th>apps/talos (3)</th>',
    );
    expect(html.indexOf('apps/talos (3)')).toBeLessThan(html.indexOf('apps/pragma (2)'));
  });

  it('lists the factory stations in line order with one column', () => {
    const html = renderDefault();
    expect(html).toContain('<tr><th></th><th>defects</th></tr><tr><th>gates (1)</th>');
    expect(html.indexOf('gates (1)')).toBeLessThan(html.indexOf('hooks (1)'));
    expect(html).not.toContain('<th>spec (');
  });

  it('lists each recurrence as a chain of links', () => {
    const html = renderDefault();
    expect(html).toContain(
      '<ol><li><strong>2 entries</strong>, 2026-09-01 to 2026-09-02: <a href="https://github.com/hugoleborso/borso.fr/blob/main/docs/dantotsus/first.md">first</a> → <a href="https://github.com/hugoleborso/borso.fr/blob/main/docs/dantotsus/second.md">second</a></li></ol>',
    );
  });

  it('says so when nothing is engaged, nothing is counted and nothing recurs', () => {
    const empty = renderWeakPointPage(
      buildInput({
        engaged: [{ ...ENGAGED, id: 'never' }],
        weeklyCounts: new Map(),
        recurrences: [],
      }),
    );
    expect(empty).toContain('<p>no occurrence yet. Target: zero per week.</p>');
    expect(empty).toContain('0 occurrence(s) recorded');
    expect(empty).toContain('<p>No entry names an earlier one in <code>recurs:</code>.</p>');
    expect(renderWeakPointPage(buildInput({ engaged: [] }))).toContain(
      '<p>No weak point is engaged.</p>',
    );
  });

  it('scales the bars to the busiest week, and to one when every week is zero', () => {
    const series = [
      { weekStart: '2026-09-28', count: 1 },
      { weekStart: '2026-10-05', count: 3 },
    ];
    const scaled = renderWeakPointPage(
      buildInput({ weeklyCounts: new Map([['gate-measures-nothing', series]]) }),
    );
    expect(scaled).toContain('style="height:33%"');
    const zeros = renderWeakPointPage(
      buildInput({
        weeklyCounts: new Map([['gate-measures-nothing', [{ weekStart: '2026-10-05', count: 0 }]]]),
      }),
    );
    expect(zeros).toContain('style="height:0%"');
  });

  it('keeps each row and each map to its own dots, and joins the parts without separators', () => {
    const page = renderWeakPointPage(
      buildInput({
        placed: [
          place(buildDot('one'), 'factory', 'gates', 'defects'),
          place(buildDot('two'), 'factory', 'gates', 'defects'),
          place(buildDot('three'), 'factory', 'hooks', 'defects'),
          place(buildDot('stray'), 'product', 'gates', 'defects'),
        ],
        engaged: [ENGAGED, { ...ENGAGED, id: 'second-one', title: 'Second one' }],
        weeklyCounts: new Map([
          [
            'gate-measures-nothing',
            [
              { weekStart: '2026-09-21', count: 1 },
              { weekStart: '2026-09-28', count: 4 },
              { weekStart: '2026-10-05', count: 2 },
            ],
          ],
        ]),
        recurrences: [
          { slugs: ['a'], firstDate: '2026-09-01', lastDate: '2026-09-01' },
          { slugs: ['b'], firstDate: '2026-09-02', lastDate: '2026-09-02' },
        ],
      }),
    );
    expect(page).toContain(
      `<tr><th></th><th>defects</th></tr><tr><th>gates (2)</th><td class="cell">${renderRecentDot('one')}${renderRecentDot('two')}</td></tr><tr><th>hooks (1)</th><td class="cell">${renderRecentDot('three')}</td></tr></table></div>`,
    );
    expect(page).toContain(
      '<div class="bars"><span class="bar" style="height:25%" title="week of 2026-09-21: 1"></span><span class="bar" style="height:100%" title="week of 2026-09-28: 4"></span><span class="bar" style="height:50%" title="week of 2026-10-05: 2"></span></div><p>2 in the week of 2026-10-05.',
    );
    expect(page).toContain('Target: zero per week.</p>\n<h3>Second one');
    expect(page).toContain(
      '2026-09-01: <a href="https://github.com/hugoleborso/borso.fr/blob/main/docs/dantotsus/a.md">a</a></li><li><strong>1 entries',
    );
  });
});
