import { escapeHtml, renderQualityPage } from './quality-page.core';
import { type FiledWall, type FrictionBoard, type FrictionLine } from './working-conditions.core';

const AREA_INTENTS: readonly (readonly [string, string])[] = [
  [
    'Build',
    'The local loop: an agent can set the project up, run it, test it and read its errors without help.',
  ],
  [
    'Observe',
    'Seeing what the system did: an error names its cause, and a failure does not read as a success.',
  ],
  [
    'Ship',
    'Merged code reaches production without friction, through checks an agent can trigger and read.',
  ],
];

function renderLine(line: FrictionLine): string {
  return `<li><code>${escapeHtml(line.writer)}</code> in ${escapeHtml(line.task)}: ${escapeHtml(line.text)}</li>`;
}

function renderWall(filed: FiledWall): string {
  return `<h3>${escapeHtml(filed.wall.description)} <code>${escapeHtml(filed.wall.id)}</code></h3>
<p>${String(filed.agents)} agent(s) across ${String(filed.tasks)} task(s), ${String(filed.lines.length)} line(s).</p>
<details><summary>The lines</summary><ul>${filed.lines.map(renderLine).join('')}</ul></details>`;
}

function renderArea(area: string, intent: string, board: FrictionBoard): string {
  const walls = board.walls.filter((filed) => filed.wall.area === area);
  const body =
    walls.length === 0 ? '<p>No friction filed here.</p>' : walls.map(renderWall).join('\n');
  return `<h2>${escapeHtml(area)}</h2>
<p>${escapeHtml(intent)}</p>
${body}`;
}

export function renderWorkingConditionsPage(
  board: FrictionBoard,
  now: string,
  sources: number,
): string {
  const filedLines = board.walls.reduce((sum, filed) => sum + filed.lines.length, 0);
  const unfiled =
    board.unfiled.length === 0
      ? '<p>Every line is filed.</p>'
      : `<ul>${board.unfiled.map(renderLine).join('')}</ul>`;
  return renderQualityPage(
    'Agent working conditions',
    `<p>Generated by scripts/quality/working-conditions.ts on ${now} from ${String(sources)} archived friction file(s). ${String(filedLines)} line(s) are filed under ${String(board.walls.length)} wall(s), ranked by how many distinct agents hit each one, then by how many tasks. The walls are written in docs/quality/working-conditions.md.</p>
${AREA_INTENTS.map(([area, intent]) => renderArea(area, intent, board)).join('\n')}
<h2>Unfiled</h2>
<p>Lines no wall matched. Three lines about the same thing are a wall to add.</p>
${unfiled}`,
  );
}
