import { describe, expect, it } from 'vitest';
import { renderWorkingConditionsPage } from './working-conditions-page.core';
import { fileFriction, type Wall } from './working-conditions.core';

const WALLS: readonly Wall[] = [
  {
    id: 'shared-database',
    area: 'Build',
    description: 'Agents share <one> database',
    terms: ['postgres'],
  },
  {
    id: 'conflicts',
    area: 'Ship',
    description: 'A conflicted pull request runs no CI',
    terms: ['conflicted'],
  },
];

function renderDefault(): string {
  const board = fileFriction(
    [
      { task: 'pragma/a', writer: 'main', text: 'one local postgres' },
      { task: 'pragma/b', writer: 'feat', text: 'postgres & a race' },
      { task: 'meta/c', writer: 'main', text: 'a conflicted pr' },
      { task: 'meta/c', writer: 'main', text: 'nothing here' },
    ],
    WALLS,
  );
  return renderWorkingConditionsPage(board, '2026-10-10', 4);
}

describe('renderWorkingConditionsPage', () => {
  it('opens with the title and what the board was built from', () => {
    const html = renderDefault();
    expect(html).toContain('<h1>Agent working conditions</h1>');
    expect(html).toContain(
      'Generated by scripts/quality/working-conditions.ts on 2026-10-10 from 4 archived friction file(s). 3 line(s) are filed under 2 wall(s),',
    );
  });

  it('files each wall under its area, with its counts and its lines', () => {
    const html = renderDefault();
    expect(html).toContain(
      '<h2>Build</h2>\n<p>The local loop: an agent can set the project up, run it, test it and read its errors without help.</p>',
    );
    expect(html).toContain(
      '<h3>Agents share &lt;one&gt; database <code>shared-database</code></h3>\n<p>2 agent(s) across 2 task(s), 2 line(s).</p>',
    );
    expect(html).toContain('<li><code>feat</code> in pragma/b: postgres &amp; a race</li>');
    expect(html.indexOf('<h2>Build</h2>')).toBeLessThan(html.indexOf('shared-database'));
    expect(html.indexOf('<h2>Ship</h2>')).toBeLessThan(html.indexOf('<code>conflicts</code>'));
  });

  it('says so for an area with no wall, and lists the unfiled lines', () => {
    const html = renderDefault();
    expect(html).toContain(
      '<h2>Observe</h2>\n<p>Seeing what the system did: an error names its cause, and a failure does not read as a success.</p>\n<p>No friction filed here.</p>',
    );
    expect(html).toContain(
      '<h2>Unfiled</h2>\n<p>Lines no wall matched. Three lines about the same thing are a wall to add.</p>\n<ul><li><code>main</code> in meta/c: nothing here</li></ul>',
    );
  });

  it('says every line is filed when none is left over', () => {
    const filed = renderWorkingConditionsPage(fileFriction([], WALLS), '2026-10-10', 0);
    expect(filed).toContain('<p>Every line is filed.</p>');
    expect(filed).toContain(
      'Ship</h2>\n<p>Merged code reaches production without friction, through checks an agent can trigger and read.</p>',
    );
  });

  it('joins lines, walls and areas without stray separators', () => {
    const walls: readonly Wall[] = [
      { id: 'first', area: 'Build', description: 'First wall', terms: ['alpha'] },
      { id: 'second', area: 'Build', description: 'Second wall', terms: ['beta'] },
    ];
    const board = fileFriction(
      [
        { task: 't', writer: 'w', text: 'alpha one' },
        { task: 't', writer: 'w', text: 'alpha two' },
        { task: 't', writer: 'x', text: 'beta' },
        { task: 't', writer: 'w', text: 'loose one' },
        { task: 't', writer: 'w', text: 'loose two' },
      ],
      walls,
    );
    const html = renderWorkingConditionsPage(board, '2026-10-10', 1);
    expect(html).toContain(
      '<ul><li><code>w</code> in t: alpha one</li><li><code>w</code> in t: alpha two</li></ul></details>\n<h3>Second wall',
    );
    expect(html).toContain('</details>\n<h2>Observe</h2>');
    expect(html).toContain('<p>No friction filed here.</p>\n<h2>Ship</h2>');
    expect(html).toContain(
      '<ul><li><code>w</code> in t: loose one</li><li><code>w</code> in t: loose two</li></ul>',
    );
  });
});
