#!/usr/bin/env tsx
/**
 * Reports where the repository has two spellings for one idea, and fails when
 * a third appears.
 *
 * Usage:
 *   pnpm exec tsx scripts/standards/convention-drift.ts            # write the report
 *   pnpm exec tsx scripts/standards/convention-drift.ts --check    # gate
 *   pnpm exec tsx scripts/standards/convention-drift.ts --accept   # lower the baseline
 *
 * `--check` compares against `docs/standards/convention-baseline.json` and
 * fails only on an increase. The existing divergences are a backlog nobody
 * needs to clear this afternoon; the next one is a decision being taken by
 * accident, and that is the thing worth stopping.
 *
 * `--accept` rewrites the baseline. Run it after fixing a divergence, never to
 * make a failure go away — the diff is small and a reviewer will read it.
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { inferLayer, isTestFile } from '../../.claude/skills/blueprint/blueprint-utils.js';
import {
  buildBaseline,
  countMinorityFiles,
  countSuffixes,
  listDivergences,
  listRatchetFailures,
  listStaleBaselineKeys,
  type BaselineCounts,
  type FileFact,
} from './conventions.core';

const REPOSITORY_ROOT = process.cwd();
const REPORT_PATH = join(REPOSITORY_ROOT, 'docs', 'standards', 'convention-drift.md');
const BASELINE_PATH = join(REPOSITORY_ROOT, 'docs', 'standards', 'convention-baseline.json');
const SOURCE_PATH_PATTERN = /^(apps|infra)\/.*\.(ts|tsx)$/;
const EXPORTED_HOOK_PATTERN = /export\s+(?:async\s+)?function\s+use[A-Z]/;
const EXPORTED_HOOK_CONST_PATTERN = /export\s+const\s+use[A-Z][A-Za-z0-9]*\s*[:=]/;

function listSourceFiles(): readonly string[] {
  return execFileSync('git', ['ls-files'], { cwd: REPOSITORY_ROOT, encoding: 'utf8' })
    .split('\n')
    .filter((path) => SOURCE_PATH_PATTERN.test(path))
    .filter((path) => !isTestFile(path))
    .filter((path) => !path.endsWith('.d.ts'));
}

function readFileFacts(): readonly FileFact[] {
  return listSourceFiles().map((path) => {
    const contents = readFileSync(join(REPOSITORY_ROOT, path), 'utf8');
    return {
      path,
      layer: inferLayer(path),
      basename: basename(path),
      exportsHook:
        EXPORTED_HOOK_PATTERN.test(contents) || EXPORTED_HOOK_CONST_PATTERN.test(contents),
    };
  });
}

function readBaseline(): BaselineCounts {
  if (!existsSync(BASELINE_PATH)) return {};
  const parsed: unknown = JSON.parse(readFileSync(BASELINE_PATH, 'utf8'));
  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) return {};
  const counts: Record<string, number> = {};
  for (const [key, value] of Object.entries(parsed)) {
    if (typeof value === 'number') counts[key] = value;
  }
  return counts;
}

const GENERATED_BANNER =
  '<!-- Generated by scripts/standards/convention-drift.ts. Do not edit by hand. -->';

const RARE_SUFFIX_THRESHOLD = 3;

function renderReport(facts: readonly FileFact[]): string {
  const divergences = listDivergences(facts);
  const suffixes = countSuffixes(facts);
  const lines: string[] = [
    GENERATED_BANNER,
    '',
    '# Convention drift',
    '',
    'Questions this repository has answered more than one way.',
    '',
    'Everything in `docs/standards/` is a question somebody decided. This page',
    'is the opposite: a question nobody decided, where the tree has quietly',
    'answered it twice. A lint rule cannot find these, because a lint rule needs',
    'the answer first. These are derived from the tree, so each one is a rule',
    'waiting to be written, and the cheap moment to write it is now rather than',
    'at twenty files.',
    '',
    '`convention-baseline.json` holds the current count per question and the',
    'gate fails only on an increase. Fixing one and running `--accept` lowers it.',
    '',
    `Read from ${String(facts.length)} source file(s).`,
    '',
  ];

  if (divergences.length === 0) {
    lines.push('Every question the tree can be asked has one answer.', '');
  }

  for (const divergence of divergences) {
    lines.push(`## ${divergence.question}`, '');
    lines.push(
      `\`${divergence.key}\` — ${String(countMinorityFiles(divergence))} file(s) outside the majority spelling.`,
      '',
    );
    lines.push('| Spelling | Files | For example |', '| --- | --- | --- |');
    for (const variant of divergence.variants) {
      lines.push(
        `| ${variant.name} | ${String(variant.count)} | ${variant.examples.map((path) => `\`${path}\``).join(', ')} |`,
      );
    }
    lines.push('');
  }

  lines.push(
    '## Every suffix in use',
    '',
    '`docs/standards/01-naming.md` documents eight. A suffix carried by fewer',
    `than ${String(RARE_SUFFIX_THRESHOLD)} files is either a convention nobody wrote down or an accident.`,
    '',
    '| Suffix | Files |',
    '| --- | --- |',
  );
  for (const suffix of suffixes) {
    const rare = suffix.count < RARE_SUFFIX_THRESHOLD ? ' — rare' : '';
    lines.push(`| \`.${suffix.name}.ts\` | ${String(suffix.count)}${rare} |`);
  }
  lines.push('');
  return lines.join('\n');
}

function main(): void {
  const facts = readFileFacts();
  const divergences = listDivergences(facts);
  const current = buildBaseline(divergences);
  const rendered = renderReport(facts);

  if (process.argv.includes('--accept')) {
    writeFileSync(BASELINE_PATH, `${JSON.stringify(current, null, 2)}\n`);
    writeFileSync(REPORT_PATH, rendered);
    console.log(`Baseline accepted: ${String(Object.keys(current).length)} question(s) tracked.`);
    return;
  }

  const baseline = readBaseline();
  const failures = listRatchetFailures(baseline, current);
  const stale = listStaleBaselineKeys(baseline, current);

  if (process.argv.includes('--check')) {
    // The ratchet is reported before staleness. A new spelling and a stale
    // report arrive together, and "regenerate the page" is not the message
    // somebody needs when the actual finding is that they just answered a
    // settled question a second way.
    for (const failure of failures) {
      console.error(
        `  ${failure.key}: ${String(failure.was)} file(s) disagreed, now ${String(failure.now)}.`,
      );
    }
    if (failures.length > 0) {
      console.error('');
      console.error('  A new spelling for a question the tree had already answered.');
      console.error('  Name the new file the way the majority does, or decide the other way');
      console.error('  and run `--accept` with the rename in the same commit.');
      process.exitCode = 1;
      return;
    }
    const onDisk = existsSync(REPORT_PATH) ? readFileSync(REPORT_PATH, 'utf8') : '';
    if (onDisk !== rendered) {
      console.error(
        '  docs/standards/convention-drift.md is out of date. Run `pnpm exec tsx scripts/standards/convention-drift.ts`.',
      );
      process.exitCode = 1;
      return;
    }
    for (const key of stale) console.log(`  ${key} is gone; run --accept to trim the baseline.`);
    console.log('No question gained a new answer.');
    return;
  }

  writeFileSync(REPORT_PATH, rendered);
  console.log(
    `Wrote docs/standards/convention-drift.md (${String(divergences.length)} question(s) with more than one answer).`,
  );
  for (const failure of failures) {
    console.log(`  ${failure.key}: ${String(failure.was)} -> ${String(failure.now)}`);
  }
}

main();
