export interface FileHistory {
  readonly path: string;
  readonly commits: number;
  readonly layer: string;
  readonly followsAPattern: boolean;
}

export interface Hotspot {
  readonly path: string;
  readonly commits: number;
  readonly layer: string;
  readonly weaknesses: readonly string[];
  readonly risk: number;
}

const NO_PATTERN = 'follows no recorded pattern';
const NO_LAYER = 'the path does not say what the file is';
const UNKNOWN_LAYER = 'unknown';

export function readWeaknesses(history: FileHistory): readonly string[] {
  const weaknesses: string[] = [];
  if (!history.followsAPattern) weaknesses.push(NO_PATTERN);
  if (history.layer === UNKNOWN_LAYER) weaknesses.push(NO_LAYER);
  return weaknesses;
}

export function rankHotspots(histories: readonly FileHistory[]): readonly Hotspot[] {
  return histories
    .map((history) => {
      const weaknesses = readWeaknesses(history);
      return {
        path: history.path,
        commits: history.commits,
        layer: history.layer,
        weaknesses,
        risk: history.commits * weaknesses.length,
      };
    })
    .filter((hotspot) => hotspot.risk > 0)
    .sort((first, second) => {
      const byRisk = second.risk - first.risk;
      return byRisk === 0 ? first.path.localeCompare(second.path) : byRisk;
    });
}

export interface LayerGap {
  readonly layer: string;
  readonly unpatternedFiles: number;
  readonly churn: number;
}

export function rankLayerGaps(histories: readonly FileHistory[]): readonly LayerGap[] {
  const gaps = new Map<string, { unpatternedFiles: number; churn: number }>();
  for (const history of histories) {
    if (history.followsAPattern) continue;
    const held = gaps.get(history.layer) ?? { unpatternedFiles: 0, churn: 0 };
    held.unpatternedFiles += 1;
    held.churn += history.commits;
    gaps.set(history.layer, held);
  }
  return [...gaps.entries()]
    .map(([layer, counts]) => ({ layer, ...counts }))
    .sort((first, second) => {
      const byChurn = second.churn - first.churn;
      return byChurn === 0 ? first.layer.localeCompare(second.layer) : byChurn;
    });
}

const GENERATED_BANNER =
  '<!-- Generated by scripts/standards/hotspots.ts. Do not edit by hand. -->';

const HOTSPOTS_SHOWN = 25;
const LAYER_GAPS_SHOWN = 10;

export function renderHotspotReport(
  histories: readonly FileHistory[],
  commitsRead: number,
  headRevision: string,
): string {
  const hotspots = rankHotspots(histories);
  const gaps = rankLayerGaps(histories);
  const lines: string[] = [
    GENERATED_BANNER,
    '',
    '# Hotspots',
    '',
    'Where the next defect is most likely to come from.',
    '',
    'Every other gate here reads the code as it stands. None of them can see',
    'that one file was edited in a fifth of the recent commits and follows no',
    'recorded pattern, while another has not been touched since it was written.',
    'Those two carry very different risk and no static check tells them apart.',
    '',
    'Risk is how often a file changes, times how many things are weak about it.',
    'A file that changes constantly and follows a blueprint scores zero and does',
    'not appear, because the pattern is doing its job. So does a file that',
    'follows nothing and nobody touches.',
    '',
    'This is a report, not a gate, and there is no freshness check on it either.',
    'The input is the history, so the page changes on every commit whether or',
    'not any source moved; a staleness gate would fail every commit for a reason',
    'nobody could act on. It records the commit it was read at instead.',
    '',
    `Read at \`${headRevision}\`, from the last ${String(commitsRead)} commit(s) over ${String(histories.length)} tracked source file(s).`,
    '',
  ];

  if (hotspots.length === 0) {
    lines.push('Every file that changes often follows a recorded pattern.', '');
  } else {
    lines.push(
      '## The files',
      '',
      '| File | Commits | Layer | Weak because | Risk |',
      '| --- | --- | --- | --- | --- |',
    );
    for (const hotspot of hotspots.slice(0, HOTSPOTS_SHOWN)) {
      lines.push(
        `| \`${hotspot.path}\` | ${String(hotspot.commits)} | ${hotspot.layer} | ${hotspot.weaknesses.join('; ')} | ${String(hotspot.risk)} |`,
      );
    }
    if (hotspots.length > HOTSPOTS_SHOWN) {
      lines.push('');
      lines.push(
        `${String(hotspots.length - HOTSPOTS_SHOWN)} more file(s) score above zero and are not shown.`,
      );
    }
    lines.push('');
  }

  if (gaps.length > 0) {
    lines.push(
      '## The next blueprint worth writing',
      '',
      'Layers holding files that follow no pattern, ordered by how much work is',
      'happening in them. A pattern pays where people are already writing without',
      'one.',
      '',
      '| Layer | Files following nothing | Their commits |',
      '| --- | --- | --- |',
    );
    for (const gap of gaps.slice(0, LAYER_GAPS_SHOWN)) {
      lines.push(`| ${gap.layer} | ${String(gap.unpatternedFiles)} | ${String(gap.churn)} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}
