/**
 * Turns the facts gathered about a citation into a verdict, and renders the
 * ledger.
 *
 * Kept apart from `enforcement-ledger.ts` so the rule that decides whether a
 * claim holds is testable without an ESLint instance, a checkout, or a file
 * system.
 */

import type { Citation, CitationKind, StandardCitations } from './citations.core';

export type Verdict = 'enforced' | 'reviewer' | 'unscoped' | 'broken';

/** What the repository could be found to say about one cited mechanism. */
export interface MechanismFacts {
  /** The mechanism is registered, or the file is on disk. */
  readonly exists: boolean;
  /**
   * Where the mechanism actually runs. A rule enabled nowhere, or a script no
   * hook and no workflow invokes, is a claim with nothing behind it.
   */
  readonly activeScopes: readonly string[];
  /**
   * The scopes the mechanism could have covered. When `activeScopes` is a
   * strict subset, the rule is real but does not reach every application, which
   * is how `borso/no-outbound-call-outside-adapter` came to be dead on two
   * applications while its standard read as repository-wide.
   */
  readonly candidateScopes: readonly string[];
}

export interface ResolvedCitation {
  readonly citation: Citation;
  readonly verdict: Verdict;
  readonly detail: string;
}

const KIND_LABELS: Readonly<Record<CitationKind, string>> = {
  eslint: 'ESLint rule',
  script: 'script',
  generator: 'generator',
  gate: 'gate',
  types: 'type declaration',
  test: 'test gate',
  reviewer: 'reviewer judgement',
};

export function resolveCitation(citation: Citation, facts: MechanismFacts): ResolvedCitation {
  if (citation.kind === 'reviewer') {
    return { citation, verdict: 'reviewer', detail: 'checked by a reviewer, not by a tool' };
  }
  if (!facts.exists) {
    return {
      citation,
      verdict: 'broken',
      detail: `\`${citation.target}\` is cited by this standard and does not exist`,
    };
  }
  if (facts.activeScopes.length === 0) {
    return {
      citation,
      verdict: 'broken',
      detail: `\`${citation.target}\` exists but runs nowhere`,
    };
  }
  const missingScopes = facts.candidateScopes.filter(
    (scope) => !facts.activeScopes.includes(scope),
  );
  if (missingScopes.length > 0) {
    return {
      citation,
      verdict: 'unscoped',
      detail: `runs on ${facts.activeScopes.join(', ')}; not on ${missingScopes.join(', ')}`,
    };
  }
  return { citation, verdict: 'enforced', detail: facts.activeScopes.join(', ') };
}

export interface OrphanMechanism {
  readonly kind: CitationKind;
  readonly target: string;
}

export interface LedgerInput {
  readonly standards: readonly StandardCitations[];
  readonly resolutionsByStandard: ReadonlyMap<string, readonly ResolvedCitation[]>;
  /** A mechanism that exists and that no standard claims. */
  readonly orphans: readonly OrphanMechanism[];
}

export interface LedgerProblem {
  readonly standard: string;
  readonly message: string;
}

export function selectLedgerProblems(input: LedgerInput): readonly LedgerProblem[] {
  const problems: LedgerProblem[] = [];
  for (const standard of input.standards) {
    for (const resolved of input.resolutionsByStandard.get(standard.standard) ?? []) {
      if (resolved.verdict === 'broken' || resolved.verdict === 'unscoped') {
        problems.push({ standard: standard.standard, message: resolved.detail });
      }
    }
    for (const bullet of standard.unmarkedBullets) {
      problems.push({
        standard: standard.standard,
        message: `this bullet opens with no citation marker: "${bullet}"`,
      });
    }
  }
  for (const orphan of input.orphans) {
    problems.push({
      standard: '(none)',
      message: `\`${orphan.target}\` runs and no standard says why`,
    });
  }
  return problems;
}

const VERDICT_MARKS: Readonly<Record<Verdict, string>> = {
  enforced: 'yes',
  reviewer: 'reviewer',
  unscoped: 'partly',
  broken: 'NO',
};

function escapeTableCell(text: string): string {
  return text.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

const GENERATED_BANNER =
  '<!-- Generated by scripts/standards/enforcement-ledger.ts. Do not edit by hand. -->';

export function renderLedger(input: LedgerInput): string {
  const lines: string[] = [
    GENERATED_BANNER,
    '',
    '# Enforcement ledger',
    '',
    'Every mechanism the standards claim, and whether it exists, where it runs,',
    'and which applications it reaches.',
    '',
    'This page is generated. `scripts/standards/enforcement-ledger.ts --check`',
    'regenerates it and fails when a standard cites a rule that is not enabled,',
    'a script no hook invokes, a workflow that is not there, or when a mechanism',
    'runs and no standard explains it. So a standard cannot claim enforcement it',
    'does not have, which is the failure this page was written to end.',
    '',
    '`partly` is not a pass. It means the mechanism is real and does not reach',
    'every application the standard covers.',
    '',
  ];

  let enforcedCount = 0;
  let reviewerCount = 0;
  for (const standard of input.standards) {
    const resolutions = input.resolutionsByStandard.get(standard.standard) ?? [];
    lines.push(`## ${standard.title}`, '');
    lines.push(`\`docs/standards/${standard.standard}\``, '');
    if (resolutions.length === 0) {
      lines.push('This standard names no enforcement.', '');
      continue;
    }
    lines.push('| Mechanism | Kind | Enforced | Where |', '| --- | --- | --- | --- |');
    for (const resolved of resolutions) {
      if (resolved.verdict === 'enforced') enforcedCount += 1;
      if (resolved.verdict === 'reviewer') reviewerCount += 1;
      const name =
        resolved.citation.kind === 'reviewer' ? '(a reviewer)' : `\`${resolved.citation.target}\``;
      lines.push(
        `| ${name} | ${KIND_LABELS[resolved.citation.kind]} | ${VERDICT_MARKS[resolved.verdict]} | ${escapeTableCell(resolved.detail)} |`,
      );
    }
    lines.push('');
  }

  lines.push(
    '## What only a reviewer can check',
    '',
    `${String(reviewerCount)} claim(s) below hand the check to a person, because no tool can make it.`,
    'They are the checklist the standards review agent works from, so the agent',
    'reviews what lint cannot rather than repeating what lint already did.',
    '',
  );
  for (const standard of input.standards) {
    const reviewerClaims = (input.resolutionsByStandard.get(standard.standard) ?? []).filter(
      (resolved) => resolved.verdict === 'reviewer',
    );
    if (reviewerClaims.length === 0) continue;
    lines.push(`### ${standard.title}`, '');
    for (const resolved of reviewerClaims) lines.push(`- ${resolved.citation.claim}`);
    lines.push('');
  }

  lines.push(
    '## Totals',
    '',
    `- ${String(enforcedCount)} claim(s) enforced by a tool`,
    `- ${String(reviewerCount)} claim(s) left to a reviewer`,
    `- ${String(selectLedgerProblems(input).length)} problem(s)`,
    '',
  );
  return `${lines.join('\n')}`;
}
