/**
 * Where each rule came from, and whether anything ever went wrong to justify it.
 *
 * This repository holds thirty-three custom lint rules and seventy-nine
 * root-cause analyses. The rules are the answer and the dantotsus are the evidence, and
 * nothing has ever put the two side by side. The published record on static
 * analysis is not encouraging about rules written from principle — Lenarduzzi
 * and colleagues found no difference in fault-proneness between clean and dirty
 * classes across 33 projects, and Netflix reports about a thousand actionable
 * findings out of a million — so "does this rule earn its place" is a question
 * worth being able to ask before writing the next one.
 *
 * It cannot be answered directly. Nobody can count the defects a rule
 * prevented, because they did not happen. What *can* be counted is provenance:
 * a rule named in a dantotsu's eradication was written because something
 * actually went wrong, and a rule no dantotsu mentions was written from
 * principle.
 *
 * Neither is a verdict. A rule written from principle can be the best one here,
 * and several obviously are. The number is an input to a conversation about the
 * next rule, which is the only place it belongs.
 */

/**
 * The part of a dantotsu that names the rule it shipped.
 *
 * Scanning the whole document credits a rule for merely appearing in one. The
 * dantotsu about a lint rule that knew only one of three spellings lists nine
 * rules as *affected by* the defect, and reading that as nine rules born from
 * nine defects inflates the count by a third. The eradication section is where
 * a dantotsu says what it shipped, so that is the only part read.
 */
export const ERADICATION_HEADING = '## Eradication';

/** The `## Eradication` section, or an empty string when there is none. */
export function readEradicationSection(markdown: string): string {
  const start = markdown.indexOf(ERADICATION_HEADING);
  if (start === -1) return '';
  const rest = markdown.slice(start + ERADICATION_HEADING.length);
  const nextHeading = rest.indexOf('\n## ');
  return nextHeading === -1 ? rest : rest.slice(0, nextHeading);
}

export interface RuleRecord {
  readonly rule: string;
  /** Dantotsu slugs whose text names this rule. */
  readonly dantotsuSlugs: readonly string[];
  /** Standards whose `## Enforced by` section cites it. */
  readonly citingStandards: readonly string[];
  /** True when `eslint.config.js` turns it on somewhere. */
  readonly enabled: boolean;
}

export type Provenance = 'from-a-defect' | 'from-principle';

export function readProvenance(record: RuleRecord): Provenance {
  return record.dantotsuSlugs.length > 0 ? 'from-a-defect' : 'from-principle';
}

export interface ProvenanceSummary {
  readonly fromDefect: number;
  readonly fromPrinciple: number;
  readonly uncited: readonly string[];
  readonly disabled: readonly string[];
}

export function summariseProvenance(records: readonly RuleRecord[]): ProvenanceSummary {
  return {
    fromDefect: records.filter((record) => readProvenance(record) === 'from-a-defect').length,
    fromPrinciple: records.filter((record) => readProvenance(record) === 'from-principle').length,
    uncited: records
      .filter((record) => record.citingStandards.length === 0)
      .map((record) => record.rule),
    disabled: records.filter((record) => !record.enabled).map((record) => record.rule),
  };
}

/**
 * Ordered so the rules with the most evidence behind them come first, then the
 * ones with none. Sorting the other way would read as a list of suspects, which
 * is not what a rule written from principle is.
 */
export function rankRecords(records: readonly RuleRecord[]): readonly RuleRecord[] {
  return [...records].sort((first, second) => {
    const byEvidence = second.dantotsuSlugs.length - first.dantotsuSlugs.length;
    return byEvidence === 0 ? first.rule.localeCompare(second.rule) : byEvidence;
  });
}

const GENERATED_BANNER =
  '<!-- Generated by scripts/standards/rule-provenance.ts. Do not edit by hand. -->';

export function renderProvenanceReport(
  records: readonly RuleRecord[],
  dantotsuCount: number,
): string {
  const summary = summariseProvenance(records);
  const ranked = rankRecords(records);
  const lines: string[] = [
    GENERATED_BANNER,
    '',
    '# Rule provenance',
    '',
    'Which rules were written because something went wrong, and which were',
    'written because something might.',
    '',
    'Nobody can count the defects a rule prevented, because they did not happen.',
    'What can be counted is where each rule came from. A rule named in a',
    "dantotsu's **eradication** section exists because a real defect reached a",
    'real branch. A rule no eradication names was written from principle.',
    '',
    'Only the eradication section is read, never the whole document. A dantotsu',
    'about a defect *in* the rules lists every rule it touched, and counting',
    'those would credit nine rules for one incident.',
    '',
    '**Neither is a verdict.** Several of the best rules here were written from',
    'principle, before anything had gone wrong, which is the whole point of the',
    'first rung of the eradication ladder. The number is an input to the decision',
    'about the *next* rule, and nothing else. Do not delete a rule because this',
    'page puts it in the lower half.',
    '',
    `${String(records.length)} rule(s), read against ${String(dantotsuCount)} dantotsu(s).`,
    '',
    `- ${String(summary.fromDefect)} came from a defect that actually happened.`,
    `- ${String(summary.fromPrinciple)} were written from principle.`,
    '',
  ];

  if (summary.uncited.length > 0) {
    lines.push(
      `${String(summary.uncited.length)} rule(s) no standard cites, which the enforcement ledger also fails on: ${summary.uncited.map((rule) => `\`${rule}\``).join(', ')}.`,
      '',
    );
  }
  if (summary.disabled.length > 0) {
    lines.push(
      `${String(summary.disabled.length)} rule(s) registered and enabled nowhere: ${summary.disabled.map((rule) => `\`${rule}\``).join(', ')}.`,
      '',
    );
  }

  lines.push('| Rule | Written because | Recorded in |', '| --- | --- | --- |');
  for (const record of ranked) {
    const provenance = readProvenance(record) === 'from-a-defect' ? 'a defect' : 'principle';
    const slugs =
      record.dantotsuSlugs.length === 0
        ? '—'
        : record.dantotsuSlugs.map((slug) => `[${slug}](../dantotsus/${slug}.md)`).join(', ');
    lines.push(`| \`${record.rule}\` | ${provenance} | ${slugs} |`);
  }
  lines.push('');
  return lines.join('\n');
}
