import { describe, expect, it } from 'vitest';
import {
  rankRecords,
  readEradicationSection,
  readProvenance,
  renderProvenanceReport,
  summariseProvenance,
  type RuleRecord,
} from './provenance.core';

function buildRecord(overrides: Partial<RuleRecord> = {}): RuleRecord {
  return {
    rule: 'borso/no-use-effect',
    dantotsuSlugs: [],
    citingStandards: ['07-state-and-effects.md'],
    enabled: true,
    ...overrides,
  };
}

describe('readEradicationSection', () => {
  it('reads only the eradication section, stopping at the next heading', () => {
    const markdown = [
      '# A title',
      '',
      '## Symptom',
      '',
      'names borso/a',
      '',
      '## Eradication',
      '',
      'ships borso/b',
      '',
      '## What to check next time',
      '',
      'names borso/c',
      '',
    ].join('\n');
    expect(readEradicationSection(markdown)).toBe('\n\nships borso/b\n');
  });

  it('reads to the end, last character included, when the section is last', () => {
    expect(readEradicationSection('## Eradication\n\nships borso/b')).toBe('\n\nships borso/b');
  });

  it('stops at a heading that follows the eradication heading immediately', () => {
    const markdown = '## Eradication \n## What to check next time\n\nnames borso/c\n';
    expect(readEradicationSection(markdown)).toBe(' ');
  });

  it('reads nothing from a dantotsu with no eradication section', () => {
    expect(readEradicationSection('# A title\n\n## Symptom\n\nprose\n')).toBe('');
  });
});

describe('readProvenance', () => {
  it('reads a rule an eradication names as coming from a defect', () => {
    expect(readProvenance(buildRecord({ dantotsuSlugs: ['a-slug'] }))).toBe('from-a-defect');
  });

  it('reads a rule no eradication names as coming from principle', () => {
    expect(readProvenance(buildRecord())).toBe('from-principle');
  });
});

describe('summariseProvenance', () => {
  it('counts both origins', () => {
    const summary = summariseProvenance([
      buildRecord({ rule: 'borso/a', dantotsuSlugs: ['x'] }),
      buildRecord({ rule: 'borso/b', dantotsuSlugs: ['y'] }),
      buildRecord({ rule: 'borso/c' }),
    ]);
    expect(summary.fromDefect).toBe(2);
    expect(summary.fromPrinciple).toBe(1);
  });

  it('names a rule no standard cites', () => {
    const summary = summariseProvenance([buildRecord({ rule: 'borso/a', citingStandards: [] })]);
    expect(summary.uncited).toEqual(['borso/a']);
  });

  it('names a rule that is registered and running nowhere', () => {
    const summary = summariseProvenance([buildRecord({ rule: 'borso/a', enabled: false })]);
    expect(summary.disabled).toEqual(['borso/a']);
  });
});

describe('rankRecords', () => {
  it('puts the rules with the most evidence first, against alphabetical order', () => {
    const ranked = rankRecords([
      buildRecord({ rule: 'borso/a', dantotsuSlugs: ['x'] }),
      buildRecord({ rule: 'borso/b', dantotsuSlugs: ['x', 'y'] }),
    ]);
    expect(ranked.map((record) => record.rule)).toEqual(['borso/b', 'borso/a']);
  });

  it('orders equal evidence by rule name, so the page is stable', () => {
    const ranked = rankRecords([
      buildRecord({ rule: 'borso/zebra' }),
      buildRecord({ rule: 'borso/alpha' }),
    ]);
    expect(ranked.map((record) => record.rule)).toEqual(['borso/alpha', 'borso/zebra']);
  });
});

describe('renderProvenanceReport', () => {
  it('renders the whole page for one rule written from principle', () => {
    expect(renderProvenanceReport([buildRecord()], 79).split('\n')).toEqual([
      '<!-- Generated by scripts/standards/rule-provenance.ts. Do not edit by hand. -->',
      '',
      '# Rule provenance',
      '',
      'Which rules were written because something went wrong, and which were',
      'written because something might.',
      '',
      'Nobody can count the defects a rule prevented, because they did not happen.',
      'What can be counted is where each rule came from. A rule named in a',
      "dantotsu's **eradication** section exists because a real defect reached a",
      'real branch. A rule no eradication names was written from principle.',
      '',
      'Only the eradication section is read, never the whole document. A dantotsu',
      'about a defect *in* the rules lists every rule it touched, and counting',
      'those would credit nine rules for one incident.',
      '',
      '**Neither is a verdict.** Several of the best rules here were written from',
      'principle, before anything had gone wrong, which is the whole point of the',
      'first rung of the eradication ladder. The number is an input to the decision',
      'about the *next* rule, and nothing else. Do not delete a rule because this',
      'page puts it in the lower half.',
      '',
      '1 rule(s), read against 79 dantotsu(s).',
      '',
      '- 0 came from a defect that actually happened.',
      '- 1 were written from principle.',
      '',
      '| Rule | Written because | Recorded in |',
      '| --- | --- | --- |',
      '| `borso/no-use-effect` | principle | — |',
      '',
    ]);
  });

  it('renders the whole page, both warnings included, for a flagged pair of rules', () => {
    const rendered = renderProvenanceReport(
      [
        buildRecord({
          rule: 'borso/a',
          dantotsuSlugs: ['a-slug', 'b-slug'],
          citingStandards: [],
          enabled: false,
        }),
        buildRecord({ rule: 'borso/b', citingStandards: [], enabled: false }),
      ],
      79,
    );
    expect(rendered.split('\n')).toEqual([
      '<!-- Generated by scripts/standards/rule-provenance.ts. Do not edit by hand. -->',
      '',
      '# Rule provenance',
      '',
      'Which rules were written because something went wrong, and which were',
      'written because something might.',
      '',
      'Nobody can count the defects a rule prevented, because they did not happen.',
      'What can be counted is where each rule came from. A rule named in a',
      "dantotsu's **eradication** section exists because a real defect reached a",
      'real branch. A rule no eradication names was written from principle.',
      '',
      'Only the eradication section is read, never the whole document. A dantotsu',
      'about a defect *in* the rules lists every rule it touched, and counting',
      'those would credit nine rules for one incident.',
      '',
      '**Neither is a verdict.** Several of the best rules here were written from',
      'principle, before anything had gone wrong, which is the whole point of the',
      'first rung of the eradication ladder. The number is an input to the decision',
      'about the *next* rule, and nothing else. Do not delete a rule because this',
      'page puts it in the lower half.',
      '',
      '2 rule(s), read against 79 dantotsu(s).',
      '',
      '- 1 came from a defect that actually happened.',
      '- 1 were written from principle.',
      '',
      '2 rule(s) no standard cites, which the enforcement ledger also fails on: `borso/a`, `borso/b`.',
      '',
      '2 rule(s) registered and enabled nowhere: `borso/a`, `borso/b`.',
      '',
      '| Rule | Written because | Recorded in |',
      '| --- | --- | --- |',
      '| `borso/a` | a defect | [a-slug](../dantotsus/a-slug.md), [b-slug](../dantotsus/b-slug.md) |',
      '| `borso/b` | principle | — |',
      '',
    ]);
  });

  it('says nothing about uncited or disabled rules when there are none', () => {
    const rendered = renderProvenanceReport([buildRecord()], 79);
    expect(rendered).not.toContain('no standard cites');
    expect(rendered).not.toContain('enabled nowhere');
  });
});
