import {
  LOCALITY_NAME,
  STRENGTH_RANK,
  summariseByKind,
  summariseByWorkspace,
} from './scoring.core';
import type { Ceilings, Finding, Metrics, OrphanCacheKey, SourceFile } from './connascence.types';

export interface Measured {
  readonly findings: readonly Finding[];
  readonly index: ReadonlyMap<string, SourceFile>;
  readonly fileCount: number;
  readonly lineCount: number;
  readonly metrics: Metrics;
  readonly orphans: readonly OrphanCacheKey[];
}

const GENERATED_BANNER =
  '<!-- Generated by scripts/standards/connascence.ts. Do not edit by hand. -->';
const WORST_FINDINGS_SHOWN = 30;
const SUBJECT_WIDTH = 70;

export function renderReport(measured: Measured, ceilings: Ceilings): string {
  const lines: string[] = [
    GENERATED_BANNER,
    '',
    '# Connascence',
    '',
    `Read from ${String(measured.fileCount)} source file(s) under \`apps/\` and \`infra/\`, tests excluded.`,
    '',
    '## By kind',
    '',
    '| Kind | Strength rank | Findings | Sites | Score |',
    '| --- | --- | --- | --- | --- |',
  ];
  for (const summary of summariseByKind(measured.findings)) {
    lines.push(
      `| ${summary.kind} | ${String(STRENGTH_RANK[summary.kind])} | ${String(summary.findings)} | ${String(summary.sites)} | ${String(summary.score)} |`,
    );
  }
  lines.push(
    '',
    '## Absolute ceilings',
    '',
    'A ratchet only says the tree got no worse. These say it is not already past a',
    'line somebody outside this repository drew.',
    '',
    '| Metric | Measured | Ceiling | Anchor |',
    '| --- | --- | --- | --- |',
  );
  for (const [metric, reading] of Object.entries(measured.metrics)) {
    const ceiling = ceilings[metric];
    lines.push(
      `| \`${metric}\` | ${String(reading)} | ${ceiling === undefined ? 'not gated' : String(ceiling.limit)} | ${ceiling?.anchor ?? 'not gated'} |`,
    );
  }
  if (measured.orphans.length > 0) {
    lines.push('', '### Cache keys nothing reads', '');
    for (const orphan of measured.orphans) {
      lines.push(
        `- \`${orphan.path}:${String(orphan.line)}\` — ${orphan.method} on \`${orphan.root}\``,
      );
    }
  }
  lines.push('', '## By workspace', '', '| Workspace | Score |', '| --- | --- |');
  const perWorkspace = [...summariseByWorkspace(measured.findings, measured.index)].sort(
    (left, right) => right[1] - left[1],
  );
  for (const [workspace, score] of perWorkspace) {
    lines.push(`| ${workspace} | ${String(score)} |`);
  }
  lines.push(
    '',
    `## Worst ${String(WORST_FINDINGS_SHOWN)}`,
    '',
    '| Score | Kind | Locality | Degree | Subject | First site |',
    '| --- | --- | --- | --- | --- | --- |',
  );
  for (const finding of measured.findings.slice(0, WORST_FINDINGS_SHOWN)) {
    const first = finding.occurrences[0];
    const subject = finding.subject.replaceAll('|', '\\|').slice(0, SUBJECT_WIDTH);
    lines.push(
      `| ${String(finding.score)} | ${finding.kind} | ${LOCALITY_NAME[finding.locality] ?? 'unknown'} | ${String(finding.degree)} | \`${subject}\` | \`${first?.path ?? ''}:${String(first?.line ?? 0)}\` |`,
    );
  }
  lines.push('');
  return lines.join('\n');
}
