"""Compile the knowledge corpus into the lookup the knowledge hooks read, or check it.

    knowledge-triggers.py compile   write the lookup, keeping every valid entry
    knowledge-triggers.py check     fail on any entry the hooks cannot deliver

A knowledge entry is read when a hook prints it at the moment it applies, and
almost never otherwise: of 123 entries, the ones that stopped a repeat were the
few a hook or a gate printed. So every entry declares, in its front matter, the
moments it applies to, and `check` refuses an entry that declares none:

    ---
    summary: One sentence the hook prints, saying what the trap is.
    triggers:
      paths:
        - 'infra/cdk/src/**/*.ts'
      commands:
        - 'aws cloudfront get-function'
      output:
        - 'FunctionThrottledError'
    ---

`paths` are globs matched against the file a Write or an Edit targets: `**`
crosses folders, `*` and `?` do not, and a glob matches at any folder boundary,
so `infra/cdk/**` matches an absolute path or a worktree's copy too. `commands`
are regular expressions searched in a Bash command after its quoted strings and
heredoc bodies are removed, so a command that only mentions another one does
not trigger. `output` are regular expressions searched in what a Bash or MCP
call printed or failed with. Each list item sits on its own line, single-quoted
when it holds a quote, a colon or a leading symbol. The hooks match with jq, so
a pattern has to compile both here and there; `check` asks jq as well.

The lookup is an output, regenerated by the hook whenever an entry is newer
than it, so it is never committed and never stale for long.

See docs/adr/0030-knowledge-is-delivered-by-trigger.md.
"""

import json
import os
import re
import subprocess
import sys
import tempfile

SCRIPTS_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
TRIGGER_KINDS = ("paths", "commands", "output")
SUMMARY_LIMIT = 400
FRONT_MATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
LIST_ITEM = re.compile(r"^    - (.*)$")
TRIGGER_KEY = re.compile(r"^  ([a-z]+):\s*$")
TOP_KEY = re.compile(r"^([A-Za-z0-9_-]+):(.*)$")


def repository_root():
    completed = subprocess.run(
        [os.path.join(SCRIPTS_DIRECTORY, "harness-path.sh"), "--root"],
        capture_output=True,
        text=True,
        check=True,
    )
    return completed.stdout.strip()


def knowledge_directory(root):
    completed = subprocess.run(
        [os.path.join(SCRIPTS_DIRECTORY, "harness-path.sh"), "knowledge"],
        capture_output=True,
        text=True,
        check=True,
    )
    return os.path.join(root, completed.stdout.strip())


def lookup_path(root):
    return os.path.join(root, ".claude", "knowledge-triggers.json")


def unquote(scalar):
    scalar = scalar.strip()
    if len(scalar) >= 2 and scalar[0] == "'" and scalar[-1] == "'":
        return scalar[1:-1].replace("''", "'")
    if len(scalar) >= 2 and scalar[0] == '"' and scalar[-1] == '"':
        return scalar[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return scalar


def parse_front_matter(text):
    match = FRONT_MATTER.match(text)
    if not match:
        return None
    fields = {"summary": None, "triggers": {}}
    in_triggers = False
    current_kind = None
    for line in match.group(1).splitlines():
        if in_triggers:
            item = LIST_ITEM.match(line)
            key = TRIGGER_KEY.match(line)
            if item and current_kind is not None:
                fields["triggers"].setdefault(current_kind, []).append(unquote(item.group(1)))
                continue
            if key:
                current_kind = key.group(1)
                fields["triggers"].setdefault(current_kind, [])
                continue
            in_triggers = False
            current_kind = None
        top = TOP_KEY.match(line)
        if not top:
            continue
        name, value = top.group(1), top.group(2).strip()
        if name == "summary":
            fields["summary"] = unquote(value)
        elif name == "triggers" and value == "":
            in_triggers = True
    return fields


def glob_to_regex(glob):
    pattern = ""
    index = 0
    while index < len(glob):
        character = glob[index]
        if glob.startswith("**/", index):
            pattern += "(?:[^/]+/)*"
            index += 3
            continue
        if glob.startswith("**", index):
            pattern += ".*"
            index += 2
            continue
        if character == "*":
            pattern += "[^/]*"
        elif character == "?":
            pattern += "[^/]"
        else:
            pattern += re.escape(character)
        index += 1
    return "(?:^|/)" + pattern + "$"


def read_entries(directory, root):
    entries = []
    problems = []
    for name in sorted(os.listdir(directory)):
        if not name.endswith(".md") or name == "README.md":
            continue
        with open(os.path.join(directory, name), encoding="utf-8") as handle:
            fields = parse_front_matter(handle.read())
        entry_problems = []
        if fields is None:
            entry_problems.append("has no front matter")
            fields = {"summary": None, "triggers": {}}
        summary = fields["summary"]
        if not summary:
            entry_problems.append("has no `summary:`, so a hook would print a path and nothing else")
        elif len(summary) > SUMMARY_LIMIT:
            entry_problems.append(f"has a summary over {SUMMARY_LIMIT} characters; the hook prints it whole")
        unknown = sorted(set(fields["triggers"]) - set(TRIGGER_KINDS))
        if unknown:
            entry_problems.append(f"declares unknown trigger kinds {unknown}; use {list(TRIGGER_KINDS)}")
        compiled = {kind: [] for kind in TRIGGER_KINDS}
        for kind in TRIGGER_KINDS:
            for raw in fields["triggers"].get(kind, []):
                if not raw:
                    entry_problems.append(f"has an empty {kind} trigger")
                    continue
                pattern = glob_to_regex(raw) if kind == "paths" else raw
                try:
                    re.compile(pattern)
                except re.error as error:
                    entry_problems.append(f"{kind} trigger {raw!r} does not compile: {error}")
                    continue
                compiled[kind].append(pattern)
        if not any(compiled.values()):
            entry_problems.append(
                "declares no trigger, so no hook can ever deliver it; give it a path, a command or an "
                "output to recognise, merge it into the entry that has one, or delete it"
            )
        relative = os.path.relpath(os.path.join(directory, name), root)
        if entry_problems:
            problems.extend(f"{relative} {problem}" for problem in entry_problems)
            continue
        entries.append({"path": relative, "summary": summary, **compiled})
    return entries, problems


def jq_problems(entries):
    patterns = sorted({pattern for entry in entries for kind in TRIGGER_KINDS for pattern in entry[kind]})
    problems = []
    for pattern in patterns:
        completed = subprocess.run(
            ["jq", "-n", "--arg", "pattern", pattern, '"" | test($pattern)'],
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            problems.append(f"pattern {pattern!r} compiles in Python and not in jq: {completed.stderr.strip()}")
    return problems


def write_lookup(root, entries):
    destination = lookup_path(root)
    os.makedirs(os.path.dirname(destination), exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(dir=os.path.dirname(destination), prefix=".knowledge-triggers.")
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        json.dump({"entries": entries}, handle, indent=1)
    os.replace(temporary, destination)
    return destination


def main(arguments):
    mode = arguments[1] if len(arguments) > 1 else ""
    if mode not in ("compile", "check"):
        print("usage: knowledge-triggers.py compile|check", file=sys.stderr)
        return 2
    root = repository_root()
    directory = knowledge_directory(root)
    if not os.path.isdir(directory):
        if mode == "check":
            print(f"[knowledge-triggers] no knowledge folder at {directory}, nothing to check")
        return 0
    entries, problems = read_entries(directory, root)
    if mode == "compile":
        write_lookup(root, entries)
        return 0
    problems.extend(jq_problems(entries))
    if problems:
        for problem in problems:
            print(f"[knowledge-triggers] {problem}", file=sys.stderr)
        print(
            "[knowledge-triggers] an entry no hook can deliver is an entry nobody reads; "
            "see docs/adr/0030-knowledge-is-delivered-by-trigger.md for the front matter.",
            file=sys.stderr,
        )
        return 1
    print(f"[knowledge-triggers] {len(entries)} knowledge entries, each with a trigger a hook can match")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
