import { describe, expect, it } from 'vitest';
import {
  countable,
  readDeletedPlaceholders,
  isSeparatorRow,
  LIMITS,
  parseBody,
  readDetailsBlocks,
  readFencedBlocks,
  readMermaidNodes,
  readTableRows,
  renderBody,
  stripAttribution,
  validateBody,
  withoutFencedLines,
  countableLines,
  readBlocks,
  readHeadingBlocks,
  isMixingShapes,
  FEATURE_SECTIONS,
  SWEEP_SECTIONS,
} from './pr-body.core';

const ATTRIBUTION = ['', '---', '_Generated by [Claude Code](https://claude.ai/code)_'];

function draft(...lines: readonly string[]): string {
  return lines.join('\n');
}

const MINIMAL = draft('# A title', '', 'A description that says what changed.');

function repeatWords(count: number): string {
  return Array.from({ length: count }, (_unused, index) => `word${String(index)}`).join(' ');
}

describe('countable', () => {
  it('counts letters and digits and ignores punctuation and spaces', () => {
    expect(countable('ab, c! 12')).toBe(5);
  });

  it('counts accented letters, because the operator writes French', () => {
    expect(countable('éàü')).toBe(3);
  });

  it('ignores a link target while keeping the text a reader actually reads', () => {
    expect(countable('[ADR17](docs/adr/0017-a-very-long-file-name.md)')).toBe(5);
  });

  it('ignores html markup', () => {
    expect(countable('<summary>ab</summary>')).toBe(2);
  });

  it('counts nothing in an empty string', () => {
    expect(countable('')).toBe(0);
  });
});

describe('stripAttribution', () => {
  it('drops the footer and the rule above it', () => {
    expect(stripAttribution(['body', ...ATTRIBUTION])).toEqual(['body']);
  });

  it('drops the footer alone when no rule precedes it', () => {
    expect(stripAttribution(['body', '_Generated by [Claude Code](x)_'])).toEqual(['body']);
  });

  it('keeps a body that carries no footer', () => {
    expect(stripAttribution(['body'])).toEqual(['body']);
  });
});

describe('parseBody', () => {
  it('reads the title, the description and the sections', () => {
    const parsed = parseBody(draft('# T', '', 'D', '## Notable', '- one'));
    expect(parsed.title).toBe('T');
    expect(parsed.description).toBe('D');
    expect([...parsed.sections.keys()]).toEqual(['Notable']);
  });

  it('answers an empty title when no heading opens the draft', () => {
    expect(parseBody('no heading').title).toBe('');
  });
});

describe('readTableRows', () => {
  it('splits a row into trimmed cells', () => {
    expect(readTableRows(['| a | b |', 'prose'])).toEqual([['a', 'b']]);
  });
});

describe('isSeparatorRow', () => {
  it('recognises a separator and rejects a data row', () => {
    expect(isSeparatorRow(['---', ':--'])).toBe(true);
    expect(isSeparatorRow(['---', 'a'])).toBe(false);
  });
});

describe('readMermaidNodes', () => {
  it('counts each identifier once across arrows and labels', () => {
    const nodes = readMermaidNodes(['```mermaid', 'flowchart TD', 'a -->|label| b', 'b --> a', '']);
    expect([...nodes].sort()).toEqual(['a', 'b']);
  });

  it('skips a line carrying no identifier', () => {
    expect(readMermaidNodes(['-->'])).toEqual([]);
  });

  it('skips the subgraph and end keywords', () => {
    expect(readMermaidNodes(['subgraph one', 'end'])).toEqual([]);
  });
});

describe('readDetailsBlocks', () => {
  it('reads the summary and the body of each block', () => {
    const blocks = readDetailsBlocks(['<details>', '<summary>S</summary>', '', 'B', '</details>']);
    expect(blocks).toEqual([{ summary: 'S', body: 'B' }]);
  });

  it('reads a block that never opened as no block at all', () => {
    expect(readDetailsBlocks(['B', '</details>'])).toEqual([]);
  });

  it('ignores a line outside any block', () => {
    expect(readDetailsBlocks(['outside'])).toEqual([]);
  });
});

describe('readFencedBlocks and withoutFencedLines', () => {
  it('reads the lines inside a fence', () => {
    expect(readFencedBlocks(['```sh', 'run me', '```'])).toEqual([['run me']]);
  });

  it('drops the fenced lines and keeps the prose', () => {
    expect(withoutFencedLines(['prose', '```', 'code', '```'])).toEqual(['prose']);
  });
});

describe('readDeletedPlaceholders', () => {
  it('finds a placeholder GitHub would delete from a code span', () => {
    expect(readDeletedPlaceholders('run `x --name <secret>`')).toEqual(['<secret>']);
  });

  it('finds nothing in a span carrying a real value', () => {
    expect(readDeletedPlaceholders('run `x --name value`')).toEqual([]);
  });

  it('finds nothing when the body has no code span at all', () => {
    expect(readDeletedPlaceholders('plain prose')).toEqual([]);
  });
});

describe('validateBody', () => {
  it('passes a minimal draft', () => {
    expect(validateBody(MINIMAL)).toEqual([]);
  });

  it('refuses a draft with no title', () => {
    expect(validateBody('just prose')).toContainEqual({
      where: 'Title',
      problem: 'no heading line opening with a hash',
    });
  });

  it('refuses a draft with no description', () => {
    expect(validateBody('# T')).toContainEqual({
      where: 'Description',
      problem: 'no paragraph under the title',
    });
  });

  it('refuses a title over the limit', () => {
    const violations = validateBody(draft(`# ${repeatWords(20)}`, '', 'D'));
    expect(violations.some((violation) => violation.where === 'Title')).toBe(true);
  });

  it('refuses a description over the limit', () => {
    const violations = validateBody(draft('# T', '', repeatWords(60)));
    expect(violations.some((violation) => violation.where === 'Description')).toBe(true);
  });

  it('refuses a section it does not know', () => {
    const violations = validateBody(draft(MINIMAL, '## Rationale', 'text'));
    expect(violations[0]?.where).toBe('Rationale');
  });

  it('refuses a flow carrying more nodes than a reader can hold', () => {
    const edges = Array.from(
      { length: LIMITS.flowNodes + 1 },
      (_unused, index) => `n${String(index)} --> n${String(index + 1)}`,
    );
    const violations = validateBody(draft(MINIMAL, '## Flow', '```mermaid', ...edges, '```'));
    expect(violations.some((violation) => violation.where === 'Flow')).toBe(true);
  });

  it('accepts a flow within the node budget', () => {
    expect(validateBody(draft(MINIMAL, '## Flow', '```mermaid', 'a --> b', '```'))).toEqual([]);
  });

  it('refuses a decisions section with no table', () => {
    expect(validateBody(draft(MINIMAL, '## Decisions', 'prose'))).toContainEqual({
      where: 'Decisions',
      problem: 'section present with no table',
    });
  });

  it('refuses decision columns that are not the agreed ones', () => {
    const violations = validateBody(draft(MINIMAL, '## Decisions', '| What | Why |'));
    expect(violations[0]?.problem).toContain('columns must be');
  });

  it('accepts a decisions table with empty cells, because every cell may be null', () => {
    const table = draft(
      MINIMAL,
      '## Decisions',
      '| Decision | Alternative | Why | Consequences | ADR |',
      '| --- | --- | --- | --- | --- |',
      '| Deezer | MusicBrainz |  |  |  |',
    );
    expect(validateBody(table)).toEqual([]);
  });

  it('refuses a decision cell over its column limit', () => {
    const table = draft(
      MINIMAL,
      '## Decisions',
      '| Decision | Alternative | Why | Consequences | ADR |',
      '| --- | --- | --- | --- | --- |',
      `| ${repeatWords(12)} |  |  |  |  |`,
    );
    const violations = validateBody(table);
    expect(violations[0]?.where).toBe('Decisions row 1 Decision');
  });

  it('refuses more decision rows than the table allows', () => {
    const rows = Array.from({ length: LIMITS.decisionRows + 1 }, () => '| a | b | c | d | e |');
    const table = draft(
      MINIMAL,
      '## Decisions',
      '| Decision | Alternative | Why | Consequences | ADR |',
      '| --- | --- | --- | --- | --- |',
      ...rows,
    );
    const violations = validateBody(table);
    expect(violations.some((violation) => violation.problem.includes('rows, limit'))).toBe(true);
  });

  it('refuses a decision row carrying a sixth cell nobody agreed to', () => {
    const table = draft(
      MINIMAL,
      '## Decisions',
      '| Decision | Alternative | Why | Consequences | ADR |',
      '| --- | --- | --- | --- | --- |',
      `| a | b | c | d | e | ${repeatWords(30)} |`,
    );
    const violations = validateBody(table);
    expect(violations.some((violation) => violation.where.includes('column 6'))).toBe(true);
  });

  it('accepts a before-merge block holding prose and one command', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '<details>',
      '<summary>Seed the credential</summary>',
      '',
      'Spotify stays inert until the parameter exists.',
      '',
      '```sh',
      'aws ssm put-parameter --name /pragma/spotify-credentials',
      '```',
      '</details>',
    );
    expect(validateBody(section)).toEqual([]);
  });

  it('refuses a before-merge section that is not exactly one details block', () => {
    expect(validateBody(draft(MINIMAL, '## Before merge', 'bare prose'))).toContainEqual({
      where: 'Before merge',
      problem: '0 blocks, expected exactly 1',
    });
  });

  it('refuses a second command block', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '<details>',
      '<summary>S</summary>',
      '```sh',
      'one',
      '```',
      '```sh',
      'two',
      '```',
      '</details>',
    );
    expect(validateBody(section)).toContainEqual({
      where: 'Before merge',
      problem: 'more than one command block',
    });
  });

  it('refuses a comment inside the command, which is prose escaping its limit', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '<details>',
      '<summary>S</summary>',
      '```sh',
      '# seed it first',
      'aws ssm put-parameter',
      '```',
      '</details>',
    );
    expect(validateBody(section)).toContainEqual({
      where: 'Before merge',
      problem: 'command block carries a comment',
    });
  });

  it('refuses before-merge prose over the limit while ignoring the command length', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '<details>',
      '<summary>S</summary>',
      repeatWords(60),
      '</details>',
    );
    const violations = validateBody(section);
    expect(violations.some((violation) => violation.where === 'Before merge')).toBe(true);
  });

  it('accepts validation evidence within its limits', () => {
    const section = draft(
      MINIMAL,
      '## Validation',
      '<details>',
      '<summary>Long press</summary>',
      'A held press opened the dialog at phone width.',
      '</details>',
    );
    expect(validateBody(section)).toEqual([]);
  });

  it('refuses a validation title over the limit', () => {
    const section = draft(
      MINIMAL,
      '## Validation',
      '<details>',
      `<summary>${repeatWords(8)}</summary>`,
      'short',
      '</details>',
    );
    const violations = validateBody(section);
    expect(violations[0]?.where).toBe('Validation item 1 title');
  });

  it('refuses a validation body over the limit', () => {
    const section = draft(
      MINIMAL,
      '## Validation',
      '<details>',
      '<summary>S</summary>',
      repeatWords(30),
      '</details>',
    );
    expect(validateBody(section)).toContainEqual({
      where: 'Validation item 1',
      problem: '170 countable chars, limit 100',
    });
  });

  it('refuses more validation items than a reviewer will open', () => {
    const items = Array.from({ length: LIMITS.evidenceItems + 1 }, () =>
      draft('<details>', '<summary>S</summary>', 'body', '</details>'),
    );
    const violations = validateBody(draft(MINIMAL, '## Validation', ...items));
    expect(violations.some((violation) => violation.problem.includes('items, limit'))).toBe(true);
  });

  it('refuses a notable fact over the limit', () => {
    const violations = validateBody(draft(MINIMAL, '## Notable', `- ${repeatWords(30)}`));
    expect(violations[0]?.where).toBe('Notable fact 1');
  });

  it('accepts notable facts within the limit', () => {
    expect(validateBody(draft(MINIMAL, '## Notable', '- Deezer needs no key.'))).toEqual([]);
  });

  it('refuses a placeholder GitHub silently deletes', () => {
    const violations = validateBody(draft(MINIMAL, '## Notable', '- run `x --value <secret>`'));
    expect(violations.some((violation) => violation.where === 'Body')).toBe(true);
  });

  it('ignores the attribution footer when counting', () => {
    expect(validateBody(draft(MINIMAL, ...ATTRIBUTION))).toEqual([]);
  });
});

describe('renderBody', () => {
  it('drops the title heading and the footer, leaving what gets posted', () => {
    expect(renderBody(draft('# T', '', 'D', ...ATTRIBUTION))).toBe('D');
  });

  it('keeps a section heading and a comment that lives inside a command', () => {
    const rendered = renderBody(draft('# T', '', 'D', '## Notable', '```sh', '# a comment', '```'));
    expect(rendered).toContain('## Notable');
    expect(rendered).toContain('# a comment');
  });
});

describe('the exact words a violation carries', () => {
  it('names the section and the counts, because the author fixes what it names', () => {
    expect(validateBody(draft(`# ${repeatWords(20)}`, '', 'D'))).toEqual([
      { where: 'Title', problem: '110 countable chars, limit 72' },
    ]);
  });

  it('names an unknown section and lists the ones that exist', () => {
    expect(validateBody(draft(MINIMAL, '## Rationale', 'text'))).toEqual([
      {
        where: 'Rationale',
        problem:
          'unknown section, allowed: Flow, Decisions, Before merge, Validation, Notable, Inventory, Shipped, Patterns',
      },
    ]);
  });

  it('names the decision columns in order', () => {
    expect(validateBody(draft(MINIMAL, '## Decisions', '| What | Why |'))).toEqual([
      {
        where: 'Decisions',
        problem: 'columns must be Decision | Alternative | Why | Consequences | ADR',
      },
    ]);
  });

  it('names the row count against the limit', () => {
    const rows = Array.from({ length: LIMITS.decisionRows + 1 }, () => '| a | b | c | d | e |');
    expect(
      validateBody(
        draft(
          MINIMAL,
          '## Decisions',
          '| Decision | Alternative | Why | Consequences | ADR |',
          '| --- | --- | --- | --- | --- |',
          ...rows,
        ),
      ),
    ).toEqual([{ where: 'Decisions', problem: '11 rows, limit 10' }]);
  });

  it('names the node count against the limit', () => {
    const edges = Array.from(
      { length: LIMITS.flowNodes + 1 },
      (_unused, index) => `n${String(index)} --> n${String(index + 1)}`,
    );
    expect(validateBody(draft(MINIMAL, '## Flow', '```mermaid', ...edges, '```'))).toEqual([
      { where: 'Flow', problem: '12 nodes, limit 10' },
    ]);
  });

  it('names the evidence count against the limit', () => {
    const items = Array.from({ length: LIMITS.evidenceItems + 1 }, () =>
      draft('<details>', '<summary>S</summary>', 'body', '</details>'),
    );
    expect(validateBody(draft(MINIMAL, '## Validation', ...items))).toEqual([
      { where: 'Validation', problem: '11 items, limit 10' },
    ]);
  });

  it('tells the author to write a literal value in place of the placeholder', () => {
    expect(validateBody(draft(MINIMAL, '## Notable', '- run `x --value <secret>`'))).toEqual([
      {
        where: 'Body',
        problem: 'GitHub deletes the placeholder <secret>; write a literal value',
      },
    ]);
  });
});

describe('the boundary, where one more would fail', () => {
  it('accepts a title of exactly the limit', () => {
    expect(validateBody(draft(`# ${'a'.repeat(LIMITS.title)}`, '', 'D'))).toEqual([]);
  });

  it('accepts a description of exactly the limit', () => {
    expect(validateBody(draft('# T', '', 'a'.repeat(LIMITS.description)))).toEqual([]);
  });

  it('accepts a flow of exactly the node budget', () => {
    const edges = Array.from(
      { length: LIMITS.flowNodes - 1 },
      (_unused, index) => `n${String(index)} --> n${String(index + 1)}`,
    );
    expect(validateBody(draft(MINIMAL, '## Flow', '```mermaid', ...edges, '```'))).toEqual([]);
  });

  it('accepts exactly the row budget', () => {
    const rows = Array.from({ length: LIMITS.decisionRows }, () => '| a | b | c | d | e |');
    const table = draft(
      MINIMAL,
      '## Decisions',
      '| Decision | Alternative | Why | Consequences | ADR |',
      '| --- | --- | --- | --- | --- |',
      ...rows,
    );
    expect(validateBody(table)).toEqual([]);
  });

  it('accepts exactly the evidence budget', () => {
    const items = Array.from({ length: LIMITS.evidenceItems }, () =>
      draft('<details>', '<summary>S</summary>', 'body', '</details>'),
    );
    expect(validateBody(draft(MINIMAL, '## Validation', ...items))).toEqual([]);
  });

  it('accepts a decision cell of exactly its column limit', () => {
    const table = draft(
      MINIMAL,
      '## Decisions',
      '| Decision | Alternative | Why | Consequences | ADR |',
      '| --- | --- | --- | --- | --- |',
      `| ${'a'.repeat(LIMITS.decisionShortCell)} | b | c | d | e |`,
    );
    expect(validateBody(table)).toEqual([]);
  });

  it('accepts a notable fact of exactly the limit', () => {
    const fact = `- ${'a'.repeat(LIMITS.notableFact)}`;
    expect(validateBody(draft(MINIMAL, '## Notable', fact))).toEqual([]);
  });

  it('accepts before-merge prose of exactly the limit', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '<details>',
      '<summary>S</summary>',
      'a'.repeat(LIMITS.beforeMerge),
      '</details>',
    );
    expect(validateBody(section)).toEqual([]);
  });

  it('accepts a validation title of exactly the limit', () => {
    const section = draft(
      MINIMAL,
      '## Validation',
      '<details>',
      `<summary>${'a'.repeat(LIMITS.evidenceTitle)}</summary>`,
      'short',
      '</details>',
    );
    expect(validateBody(section)).toEqual([]);
  });

  it('accepts a validation body of exactly the limit', () => {
    const section = draft(
      MINIMAL,
      '## Validation',
      '<details>',
      '<summary>S</summary>',
      'a'.repeat(LIMITS.evidenceBody),
      '</details>',
    );
    expect(validateBody(section)).toEqual([]);
  });
});

describe('indentation, which a writer adds without thinking', () => {
  it('reads an indented table row', () => {
    expect(readTableRows(['  | a | b |'])).toEqual([['a', 'b']]);
  });

  it('reads a row that does not close with a pipe', () => {
    expect(readTableRows(['| a | b'])).toEqual([['a', 'b']]);
  });

  it('reads an indented mermaid line', () => {
    expect(readMermaidNodes(['    a --> b'])).toEqual(['a', 'b']);
  });

  it('reads an indented details block', () => {
    const blocks = readDetailsBlocks([
      '  <details>',
      '  <summary>S</summary>',
      '  b',
      '  </details>',
    ]);
    expect(blocks).toEqual([{ summary: 'S', body: 'b' }]);
  });

  it('reads a details block that carries no summary', () => {
    expect(readDetailsBlocks(['<details>', 'b', '</details>'])).toEqual([
      { summary: '', body: 'b' },
    ]);
  });

  it('reads an indented fence', () => {
    expect(readFencedBlocks(['  ```sh', 'run', '  ```'])).toEqual([['run']]);
  });

  it('reads an indented notable fact', () => {
    const violations = validateBody(draft(MINIMAL, '## Notable', `  - ${repeatWords(30)}`));
    expect(violations[0]?.where).toBe('Notable fact 1');
  });

  it('reads an indented comment inside the command', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '<details>',
      '<summary>S</summary>',
      '```sh',
      '  # indented comment',
      '```',
      '</details>',
    );
    expect(validateBody(section)).toContainEqual({
      where: 'Before merge',
      problem: 'command block carries a comment',
    });
  });

  it('ignores a heading inside an indented fence', () => {
    const section = draft(MINIMAL, '## Notable', '  ```sh', '  ## not a section', '  ```');
    expect(validateBody(section)).toEqual([]);
  });

  it('reads a line that is not a fact even though it ends with a dash list marker', () => {
    expect(validateBody(draft(MINIMAL, '## Notable', 'prose -'))).toEqual([]);
  });

  it('trims a section name written with a trailing space', () => {
    expect([...parseBody(draft('# T', '', 'D', '## Notable ', '- a')).sections.keys()]).toEqual([
      'Notable',
    ]);
  });

  it('trims a title written with a trailing space', () => {
    expect(parseBody(draft('# T ', '', 'D')).title).toBe('T');
  });

  it('keeps the line breaks of a description', () => {
    expect(parseBody(draft('# T', '', 'one', 'two')).description).toBe('one\ntwo');
  });

  it('keeps the line breaks of before-merge prose', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '<details>',
      '<summary>S</summary>',
      'a'.repeat(LIMITS.beforeMerge),
      'b',
      '</details>',
    );
    expect(validateBody(section)).toEqual([
      { where: 'Before merge', problem: '201 countable chars, limit 200' },
    ]);
  });
});

describe('stripAttribution edges', () => {
  it('keeps a body whose only line is the footer itself', () => {
    expect(stripAttribution(['_Generated by [Claude Code](x)_'])).toEqual([]);
  });

  it('keeps the lines after a footer that is not last', () => {
    expect(stripAttribution(['a', '_Generated by [Claude Code](x)_', 'b'])).toEqual(['a']);
  });

  it('survives a body that is blank above the rule', () => {
    expect(stripAttribution(['', '---', '_Generated by [Claude Code](x)_'])).toEqual([]);
  });

  it('drops a trailing whitespace-only line', () => {
    expect(stripAttribution(['a', '  ', '---', '_Generated by [Claude Code](x)_'])).toEqual(['a']);
  });
});

describe('the parts a careless edit would silently change', () => {
  it('treats a rule on the very first line as the start of the footer', () => {
    expect(stripAttribution(['---', '_Generated by [Claude Code](x)_'])).toEqual([]);
  });

  it('sees a fence opened with indentation, so a heading inside it stays text', () => {
    const section = draft(MINIMAL, '## Notable', '  ```sh', '## fake section', '  ```');
    expect(validateBody(section)).toEqual([]);
  });

  it('skips an indented mermaid keyword rather than counting it as a node', () => {
    expect(readMermaidNodes(['  subgraph one', '  end'])).toEqual([]);
  });

  it('keeps a closing tag that only ends a line as part of the body', () => {
    const blocks = readDetailsBlocks(['<details>', 'text</details>', '</details>']);
    expect(blocks).toEqual([{ summary: '', body: 'text</details>' }]);
  });

  it('keeps the line breaks of a details body', () => {
    const blocks = readDetailsBlocks(['<details>', 'one', 'two', '</details>']);
    expect(blocks[0]?.body).toBe('one\ntwo');
  });

  it('trims a summary written with spaces inside the tag', () => {
    expect(
      readDetailsBlocks(['<details>', '<summary> S </summary>', '</details>'])[0]?.summary,
    ).toBe('S');
  });

  it('drops indented fenced lines and keeps the prose around them', () => {
    expect(withoutFencedLines(['  ```', 'code', '  ```', 'prose'])).toEqual(['prose']);
  });

  it('counts each line of a block and adds them up', () => {
    expect(countableLines(['ab', 'c!'])).toBe(3);
  });

  it('leaves the command out of the before-merge count', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '<details>',
      '<summary>S</summary>',
      'a'.repeat(LIMITS.beforeMerge),
      '```sh',
      'aws ssm put-parameter --name /pragma/spotify-credentials --type SecureString',
      '```',
      '</details>',
    );
    expect(validateBody(section)).toEqual([]);
  });

  it('reads only list items as notable facts', () => {
    const paragraph = repeatWords(40);
    expect(validateBody(draft(MINIMAL, '## Notable', paragraph))).toEqual([]);
  });

  it('renders the body line by line, fences and section headings intact', () => {
    const rendered = renderBody(draft('# T', '', 'D', '## Notable', '  ```sh', '# cmd', '  ```'));
    expect(rendered).toBe('D\n## Notable\n  ```sh\n# cmd\n  ```');
  });
});

describe('a heading block, which is what survives the GitHub body sanitizer', () => {
  it('reads a heading and the lines under it as one block', () => {
    expect(readHeadingBlocks(['### T', 'body'])).toEqual([{ summary: 'T', body: 'body' }]);
  });

  it('closes one heading block when the next opens', () => {
    expect(readHeadingBlocks(['### A', 'one', '### B', 'two'])).toEqual([
      { summary: 'A', body: 'one' },
      { summary: 'B', body: 'two' },
    ]);
  });

  it('keeps each block line-separated and drops the blank lines around it', () => {
    const lines = ['### A', '', 'one', 'two', '', '### B', '', 'three', ''];
    expect(readHeadingBlocks(lines)).toEqual([
      { summary: 'A', body: 'one\ntwo' },
      { summary: 'B', body: 'three' },
    ]);
  });

  it('ignores the lines before the first heading', () => {
    expect(readHeadingBlocks(['loose', '### T', 'body'])).toEqual([{ summary: 'T', body: 'body' }]);
  });

  it('reads nothing from lines carrying no heading', () => {
    expect(readHeadingBlocks(['loose'])).toEqual([]);
  });

  it('trims a heading written with a trailing space', () => {
    expect(readHeadingBlocks(['### T ', 'b'])[0]?.summary).toBe('T');
  });

  it('keeps the line breaks under a heading', () => {
    expect(readHeadingBlocks(['### T', 'one', 'two'])[0]?.body).toBe('one\ntwo');
  });

  it('prefers a toggle when the section carries one', () => {
    const lines = ['<details>', '<summary>S</summary>', 'b', '</details>', '### H', 'c'];
    expect(readBlocks(lines)).toEqual([{ summary: 'S', body: 'b' }]);
  });

  it('falls back to headings when the section carries no toggle', () => {
    expect(readBlocks(['### H', 'c'])).toEqual([{ summary: 'H', body: 'c' }]);
  });

  it('accepts a before-merge section written as a heading', () => {
    const section = draft(
      MINIMAL,
      '## Before merge',
      '### Seed the credential',
      'Spotify stays inert until the parameter exists.',
      '```sh',
      'aws ssm put-parameter --name /pragma/spotify-credentials',
      '```',
    );
    expect(validateBody(section)).toEqual([]);
  });

  it('accepts validation evidence written as headings', () => {
    const section = draft(
      MINIMAL,
      '## Validation',
      '### Long press',
      'A held press opened the dialog at phone width.',
      '### Live search',
      'Deezer answered 25 ranked hits through the dev API.',
    );
    expect(validateBody(section)).toEqual([]);
  });

  it('refuses a heading-written validation body over the limit', () => {
    const section = draft(MINIMAL, '## Validation', '### T', repeatWords(30));
    expect(validateBody(section)).toContainEqual({
      where: 'Validation item 1',
      problem: '170 countable chars, limit 100',
    });
  });

  it('refuses two before-merge blocks written as headings', () => {
    const section = draft(MINIMAL, '## Before merge', '### One', 'a', '### Two', 'b');
    expect(validateBody(section)).toContainEqual({
      where: 'Before merge',
      problem: '2 blocks, expected exactly 1',
    });
  });
});

describe('the sweep shape, which a kaizen body uses instead', () => {
  const SWEEP = draft(
    '# docs: lessons from PR 1',
    '',
    'Twenty-three rows swept, twelve already eradicated.',
    '## Inventory',
    '| Decision | Rows |',
    '| --- | --- |',
    '| dantotsu | 3 |',
    '## Shipped',
    '| Entry | Level | Now impossible |',
    '| --- | --- | --- |',
    '| [a](docs/dantotsus/a.md) | 1 | A reader cannot get it wrong |',
    '## Patterns',
    '- The file excused from the gates is the one that broke.',
  );

  it('accepts a sweep body', () => {
    expect(validateBody(SWEEP)).toEqual([]);
  });

  it('refuses a body mixing a feature section into a sweep', () => {
    const mixed = draft(SWEEP, '## Notable', '- a fact');
    expect(validateBody(mixed)).toContainEqual({
      where: 'Body',
      problem: `a body is a feature (${FEATURE_SECTIONS.join(', ')}) or a sweep (${SWEEP_SECTIONS.join(', ')}), never both`,
    });
  });

  it('holds a body carrying one sweep section to the whole-body limit, mixed or not', () => {
    const mixedAndWide = draft(SWEEP, '## Notable', `- ${repeatWords(200)}`);
    const problems = validateBody(mixedAndWide)
      .filter((violation) => violation.where === 'Body')
      .map((violation) => violation.problem);
    expect(problems).toHaveLength(2);
    expect(problems.some((problem) => problem.includes('limit 700'))).toBe(true);
    expect(problems.some((problem) => problem.includes('never both'))).toBe(true);
  });

  it('holds a sweep body to the whole-body limit', () => {
    const wide = draft(SWEEP.replace('| dantotsu | 3 |', `| ${repeatWords(200)} | 3 |`));
    const violations = validateBody(wide);
    expect(violations.some((violation) => violation.where === 'Body')).toBe(true);
  });

  it('leaves a feature body free of the whole-body limit', () => {
    const wide = draft(
      MINIMAL,
      '## Notable',
      `- ${'a'.repeat(LIMITS.notableFact)}`,
      `- ${'b'.repeat(LIMITS.notableFact)}`,
      `- ${'c'.repeat(LIMITS.notableFact)}`,
      `- ${'d'.repeat(LIMITS.notableFact)}`,
      `- ${'e'.repeat(LIMITS.notableFact)}`,
      `- ${'f'.repeat(LIMITS.notableFact)}`,
      `- ${'g'.repeat(LIMITS.notableFact)}`,
      `- ${'h'.repeat(LIMITS.notableFact)}`,
    );
    expect(validateBody(wide)).toEqual([]);
  });

  it('refuses each sweep section over its own limit', () => {
    for (const [name, limit] of [
      ['Inventory', LIMITS.inventory],
      ['Shipped', LIMITS.shipped],
      ['Patterns', LIMITS.patterns],
    ] as const) {
      const body = draft('# T', '', 'D', `## ${name}`, 'a'.repeat(limit + 1));
      expect(validateBody(body)).toContainEqual({
        where: name,
        problem: `${String(limit + 1)} countable chars, limit ${String(limit)}`,
      });
    }
  });

  it('leaves a command block out of the whole-body count', () => {
    const withCode = draft(SWEEP, '', '```sh', 'a'.repeat(LIMITS.whole), '```');
    expect(validateBody(withCode)).toEqual([]);
  });
});

describe('isMixingShapes', () => {
  it('answers true only when both shapes appear', () => {
    expect(isMixingShapes(['Notable', 'Inventory'])).toBe(true);
    expect(isMixingShapes(['Notable', 'Flow'])).toBe(false);
    expect(isMixingShapes(['Inventory', 'Shipped'])).toBe(false);
    expect(isMixingShapes([])).toBe(false);
  });
});
