export interface Limits {
  readonly title: number;
  readonly description: number;
  readonly flowNodes: number;
  readonly decisionRows: number;
  readonly decisionShortCell: number;
  readonly decisionLongCell: number;
  readonly beforeMerge: number;
  readonly evidenceItems: number;
  readonly evidenceTitle: number;
  readonly evidenceBody: number;
  readonly notableFact: number;
}

export const LIMITS: Limits = {
  title: 72,
  description: 200,
  flowNodes: 10,
  decisionRows: 10,
  decisionShortCell: 50,
  decisionLongCell: 100,
  beforeMerge: 200,
  evidenceItems: 10,
  evidenceTitle: 30,
  evidenceBody: 100,
  notableFact: 100,
};

export const SECTION_NAMES = [
  'Flow',
  'Decisions',
  'Before merge',
  'Validation',
  'Notable',
] as const;
export type SectionName = (typeof SECTION_NAMES)[number];

export const DECISION_COLUMNS = ['Decision', 'Alternative', 'Why', 'Consequences', 'ADR'] as const;

export interface Violation {
  readonly where: string;
  readonly problem: string;
}

export interface ParsedBody {
  readonly title: string;
  readonly description: string;
  readonly sections: ReadonlyMap<string, readonly string[]>;
}

export interface DetailsBlock {
  readonly summary: string;
  readonly body: string;
}

const LINK_TARGET = /\]\([^)]*\)/g;
const HTML_TAG = /<[^>]*>/g;
const ALPHANUMERIC = /[\p{L}\p{N}]/gu;
const ATTRIBUTION_MARKER = '_Generated by [Claude Code]';
const HORIZONTAL_RULE = '---';
const FENCE = '```';
const PLACEHOLDER = /<[A-Za-z][A-Za-z0-9 _-]*>/;
const CODE_SPAN = /`[^`\n]+`/g;
const MERMAID_KEYWORD = /^(flowchart|graph|sequenceDiagram|subgraph|end)\b/;
const MERMAID_EDGE = /--+>|==+>|-\.->|--+|:::/;
const MERMAID_IDENTIFIER = /^[A-Za-z0-9_]+/;
const EDGE_LABEL = /\|[^|]*\|/g;
const SEPARATOR_CELL = /^:?-{2,}:?$/;
const SUMMARY_TAG = /<summary>.*<\/summary>/;
const SUMMARY_TAGS = /<\/?summary>/g;

export function countable(text: string): number {
  const withoutTargets = text.replace(LINK_TARGET, '');
  const withoutTags = withoutTargets.replace(HTML_TAG, '');
  return (withoutTags.match(ALPHANUMERIC) ?? []).length;
}

export function stripAttribution(lines: readonly string[]): readonly string[] {
  const markerIndex = lines.findIndex((line) => line.startsWith(ATTRIBUTION_MARKER));
  if (markerIndex < 0) return lines;
  const ruleIndex = lines.lastIndexOf(HORIZONTAL_RULE, markerIndex);
  const kept = lines.slice(0, ruleIndex < 0 ? markerIndex : ruleIndex);
  return kept.slice(0, kept.findLastIndex((line) => line.trim() !== '') + 1);
}

export function parseBody(source: string): ParsedBody {
  const lines = stripAttribution(source.split('\n'));
  const titleLine = lines.find((line) => line.startsWith('# ')) ?? '';
  const sections = new Map<string, string[]>();
  const description: string[] = [];
  let current: string[] | null = null;
  let isFenced = false;
  for (const line of lines) {
    if (line.trim().startsWith(FENCE)) isFenced = !isFenced;
    if (!isFenced && line.startsWith('# ')) continue;
    if (!isFenced && line.startsWith('## ')) {
      current = [];
      sections.set(line.slice(3).trim(), current);
      continue;
    }
    (current ?? description).push(line);
  }
  return { title: titleLine.slice(2).trim(), description: description.join('\n').trim(), sections };
}

export function readTableRows(lines: readonly string[]): readonly (readonly string[])[] {
  return lines
    .map((line) => line.trim())
    .filter((line) => line.startsWith('|'))
    .map((line) =>
      line
        .slice(1, line.endsWith('|') ? -1 : undefined)
        .split('|')
        .map((cell) => cell.trim()),
    );
}

export function isSeparatorRow(cells: readonly string[]): boolean {
  return cells.every((cell) => SEPARATOR_CELL.test(cell));
}

export function readMermaidNodes(lines: readonly string[]): readonly string[] {
  const identifiers = new Set<string>();
  for (const line of lines) {
    const trimmed = line.trim();
    if (MERMAID_KEYWORD.test(trimmed)) continue;
    for (const segment of trimmed.split(MERMAID_EDGE)) {
      const identifier = MERMAID_IDENTIFIER.exec(segment.replace(EDGE_LABEL, '').trim());
      if (identifier !== null) identifiers.add(identifier[0]);
    }
  }
  return [...identifiers];
}

export function readHeadingBlocks(lines: readonly string[]): readonly DetailsBlock[] {
  const blocks: DetailsBlock[] = [];
  let open: { summary: string; body: string[] } | null = null;
  for (const line of lines) {
    if (line.startsWith('### ')) {
      if (open !== null) blocks.push({ summary: open.summary, body: open.body.join('\n').trim() });
      open = { summary: line.slice(4).trim(), body: [] };
      continue;
    }
    if (open !== null) open.body.push(line);
  }
  if (open !== null) blocks.push({ summary: open.summary, body: open.body.join('\n').trim() });
  return blocks;
}

export function readBlocks(lines: readonly string[]): readonly DetailsBlock[] {
  const toggles = readDetailsBlocks(lines);
  return toggles.length > 0 ? toggles : readHeadingBlocks(lines);
}

export function readDetailsBlocks(lines: readonly string[]): readonly DetailsBlock[] {
  const blocks: DetailsBlock[] = [];
  let open: { summary: string; body: string[] } | null = null;
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('<details')) {
      open = { summary: '', body: [] };
      continue;
    }
    if (trimmed === '</details>') {
      if (open !== null) blocks.push({ summary: open.summary, body: open.body.join('\n').trim() });
      open = null;
      continue;
    }
    if (open === null) continue;
    const summary = SUMMARY_TAG.exec(trimmed);
    if (summary !== null) {
      open.summary = summary[0].replace(SUMMARY_TAGS, '').trim();
      continue;
    }
    open.body.push(line);
  }
  return blocks;
}

export function readFencedBlocks(lines: readonly string[]): readonly (readonly string[])[] {
  const blocks: string[][] = [];
  let open: string[] | null = null;
  for (const line of lines) {
    if (line.trim().startsWith(FENCE)) {
      if (open === null) open = [];
      else {
        blocks.push(open);
        open = null;
      }
      continue;
    }
    if (open !== null) open.push(line);
  }
  return blocks;
}

export function withoutFencedLines(lines: readonly string[]): readonly string[] {
  const kept: string[] = [];
  let isInside = false;
  for (const line of lines) {
    if (line.trim().startsWith(FENCE)) {
      isInside = !isInside;
      continue;
    }
    if (!isInside) kept.push(line);
  }
  return kept;
}

export function readDeletedPlaceholders(source: string): readonly string[] {
  const found: string[] = [];
  for (const [span] of source.matchAll(CODE_SPAN)) {
    const placeholder = PLACEHOLDER.exec(span);
    if (placeholder !== null) found.push(placeholder[0]);
  }
  return found;
}

export function countableLines(lines: readonly string[]): number {
  return lines.reduce((total, line) => total + countable(line), 0);
}

function overSize(where: string, size: number, limit: number, violations: Violation[]): void {
  if (size > limit) {
    violations.push({ where, problem: `${String(size)} countable chars, limit ${String(limit)}` });
  }
}

function overLimit(where: string, text: string, limit: number, violations: Violation[]): void {
  overSize(where, countable(text), limit, violations);
}

function checkDecisions(lines: readonly string[], violations: Violation[]): void {
  const rows = readTableRows(lines);
  const [header, ...rest] = rows;
  if (header === undefined) {
    violations.push({ where: 'Decisions', problem: 'section present with no table' });
    return;
  }
  if (header.join('|') !== DECISION_COLUMNS.join('|')) {
    violations.push({
      where: 'Decisions',
      problem: `columns must be ${DECISION_COLUMNS.join(' | ')}`,
    });
  }
  const dataRows = rest.filter((cells) => !isSeparatorRow(cells));
  if (dataRows.length > LIMITS.decisionRows) {
    violations.push({
      where: 'Decisions',
      problem: `${String(dataRows.length)} rows, limit ${String(LIMITS.decisionRows)}`,
    });
  }
  const cellLimits = [
    LIMITS.decisionShortCell,
    LIMITS.decisionShortCell,
    LIMITS.decisionLongCell,
    LIMITS.decisionLongCell,
    LIMITS.decisionLongCell,
  ];
  dataRows.forEach((cells, rowIndex) => {
    cells.forEach((cell, columnIndex) => {
      const limit = cellLimits[columnIndex] ?? LIMITS.decisionLongCell;
      const column = DECISION_COLUMNS[columnIndex] ?? `column ${String(columnIndex + 1)}`;
      overLimit(`Decisions row ${String(rowIndex + 1)} ${column}`, cell, limit, violations);
    });
  });
}

function checkFlow(lines: readonly string[], violations: Violation[]): void {
  const nodes = readMermaidNodes(lines);
  if (nodes.length > LIMITS.flowNodes) {
    violations.push({
      where: 'Flow',
      problem: `${String(nodes.length)} nodes, limit ${String(LIMITS.flowNodes)}`,
    });
  }
}

function checkBeforeMerge(lines: readonly string[], violations: Violation[]): void {
  const blocks = readBlocks(lines);
  if (blocks.length !== 1) {
    violations.push({
      where: 'Before merge',
      problem: `${String(blocks.length)} blocks, expected exactly 1`,
    });
    return;
  }
  const isFenced = readFencedBlocks(lines);
  if (isFenced.length > 1) {
    violations.push({ where: 'Before merge', problem: 'more than one command block' });
  }
  for (const commandLine of isFenced.flat()) {
    if (commandLine.trim().startsWith('#')) {
      violations.push({ where: 'Before merge', problem: 'command block carries a comment' });
    }
  }
  for (const block of blocks) {
    const prose = withoutFencedLines(block.body.split('\n'));
    overSize('Before merge', countableLines(prose), LIMITS.beforeMerge, violations);
  }
}

function checkValidation(lines: readonly string[], violations: Violation[]): void {
  const blocks = readBlocks(lines);
  if (blocks.length > LIMITS.evidenceItems) {
    violations.push({
      where: 'Validation',
      problem: `${String(blocks.length)} items, limit ${String(LIMITS.evidenceItems)}`,
    });
  }
  blocks.forEach((block, index) => {
    const label = `Validation item ${String(index + 1)}`;
    overLimit(`${label} title`, block.summary, LIMITS.evidenceTitle, violations);
    overLimit(label, block.body, LIMITS.evidenceBody, violations);
  });
}

function checkNotable(lines: readonly string[], violations: Violation[]): void {
  const facts = lines.filter((line) => line.trim().startsWith('- '));
  facts.forEach((fact, index) => {
    overLimit(`Notable fact ${String(index + 1)}`, fact, LIMITS.notableFact, violations);
  });
}

const SECTION_CHECKS: Record<SectionName, (lines: readonly string[], out: Violation[]) => void> = {
  Flow: checkFlow,
  Decisions: checkDecisions,
  'Before merge': checkBeforeMerge,
  Validation: checkValidation,
  Notable: checkNotable,
};

function isSectionName(name: string): name is SectionName {
  return SECTION_NAMES.some((known) => known === name);
}

export function validateBody(source: string): readonly Violation[] {
  const violations: Violation[] = [];
  const parsed = parseBody(source);
  if (parsed.title === '') {
    violations.push({ where: 'Title', problem: 'no heading line opening with a hash' });
  }
  overLimit('Title', parsed.title, LIMITS.title, violations);
  if (parsed.description === '') {
    violations.push({ where: 'Description', problem: 'no paragraph under the title' });
  }
  overLimit('Description', parsed.description, LIMITS.description, violations);
  for (const [name, lines] of parsed.sections) {
    if (!isSectionName(name)) {
      violations.push({
        where: name,
        problem: `unknown section, allowed: ${SECTION_NAMES.join(', ')}`,
      });
      continue;
    }
    SECTION_CHECKS[name](lines, violations);
  }
  for (const placeholder of readDeletedPlaceholders(source)) {
    violations.push({
      where: 'Body',
      problem: `GitHub deletes the placeholder ${placeholder}; write a literal value`,
    });
  }
  return violations;
}

export function renderBody(source: string): string {
  const lines = stripAttribution(source.split('\n'));
  const kept: string[] = [];
  let isFenced = false;
  for (const line of lines) {
    if (line.trim().startsWith(FENCE)) isFenced = !isFenced;
    if (!isFenced && line.startsWith('# ')) continue;
    kept.push(line);
  }
  return kept.join('\n').trim();
}
